import type {SidebarsConfig} from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  germanSidebar: [
    {
      type: "category",
      label: "START HERE: COURSE GUIDE",
      collapsed: false,
      items: [
        { type: "doc", id: "german/course-guide/how-this-course-works", label: "How This Course Works" },
        { type: "doc", id: "german/course-guide/learning-path", label: "Recommended Learning Path" },
        { type: "doc", id: "german/course-guide/a2-b1-roadmap", label: "A2 & B1 Roadmap" },
      ],
    },
    {
      type: "category",
      label: "GERMAN A1 - COMPLETE BEGINNER",
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Volume 1: Foundations",
          items: [
            { type: "doc", id: "german/a1/vol1-foundations/survival-kit", label: "1.0 Survival Kit: First 30 Sentences" },
            { type: "doc", id: "german/a1/vol1-foundations/alphabet-pronunciation", label: "1.1 Alphabet & Pronunciation" },
            { type: "doc", id: "german/a1/vol1-foundations/reading-compound-words", label: "1.2 Reading German Words & Compound Nouns" },
            { type: "doc", id: "german/a1/vol1-foundations/greetings-basic-comm", label: "1.3 Greetings & Basic Communication" },
            { type: "doc", id: "german/a1/vol1-foundations/personal-pronouns", label: "1.4 Personal Pronouns & Du vs. Sie" },
            { type: "doc", id: "german/a1/vol1-foundations/numbers-dates-time", label: "1.5 Numbers, Dates & Time" },
            { type: "doc", id: "german/a1/vol1-foundations/first-sentences", label: "1.6 First Sentences & Introductions" },
            { type: "doc", id: "german/a1/vol1-foundations/ordinal-numbers", label: "1.7 Numbers above 100, Ordinals & Dates" },
          ],
        },
        {
          type: "category",
          label: "Volume 2: People & Everyday Life",
          items: [
            { type: "doc", id: "german/a1/vol2-people/personal-information", label: "2.1 Asking for Personal Information" },
            { type: "doc", id: "german/a1/vol2-people/family", label: "2.2 Family & Possessives" },
            { type: "doc", id: "german/a1/vol2-people/describing-people", label: "2.3 Describing People" },
            { type: "doc", id: "german/a1/vol2-people/daily-routine", label: "2.4 Daily Routine & Separable Verbs" },
            { type: "doc", id: "german/a1/vol2-people/hobbies-free-time", label: "2.5 Hobbies & Free Time" },
            { type: "doc", id: "german/a1/vol2-people/likes-preferences", label: "2.6 Likes & Preferences" },
          ],
        },
        {
          type: "category",
          label: "Volume 3: Grammar & Sentence Builder",
          items: [
            { type: "doc", id: "german/a1/vol3-grammar/nouns-gender", label: "3.1 Nouns & Gender" },
            { type: "doc", id: "german/a1/vol3-grammar/plurals", label: "3.2 Plurals (Der Plural)" },
            { type: "doc", id: "german/a1/vol3-grammar/nominative", label: "3.3 Nominative Case" },
            { type: "doc", id: "german/a1/vol3-grammar/present-tense-verbs", label: "3.4 Present Tense Verbs" },
            { type: "doc", id: "german/a1/vol3-grammar/sein-and-haben", label: "3.5 sein & haben" },
            { type: "doc", id: "german/a1/vol3-grammar/modal-verbs", label: "3.6 Modal Verbs" },
            { type: "doc", id: "german/a1/vol3-grammar/sentence-structure-v2", label: "3.7 Sentence Structure & V2 Rule" },
            { type: "doc", id: "german/a1/vol3-grammar/questions", label: "3.8 Questions (W-Fragen & Ja/Nein)" },
            { type: "doc", id: "german/a1/vol3-grammar/accusative", label: "3.9 Accusative Case (Direct Object)" },
            { type: "doc", id: "german/a1/vol3-grammar/dative", label: "3.10 Dative Case (Indirect Object)" },
            { type: "doc", id: "german/a1/vol3-grammar/negation", label: "3.11 Negation (nicht vs. kein)" },
            { type: "doc", id: "german/a1/vol3-grammar/separable-verbs", label: "3.12 Separable Verbs" },
            { type: "doc", id: "german/a1/vol3-grammar/prepositions", label: "3.13 Basic Prepositions" },
            { type: "doc", id: "german/a1/vol3-grammar/conjunctions", label: "3.14 Conjunctions (und, oder, aber, denn)" },
            { type: "doc", id: "german/a1/vol3-grammar/imperative", label: "3.15 Imperative (Commands)" },
            { type: "doc", id: "german/a1/vol3-grammar/basic-past", label: "3.16 Basic Past (war & hatte)" },
            { type: "doc", id: "german/a1/vol3-grammar/polite-requests", label: "3.17 Polite Requests (Ich möchte / hätte gern)" },
            { type: "doc", id: "german/a1/vol3-grammar/perfekt-spoken-past", label: "3.18 Perfekt (Spoken Past)" },
            { type: "doc", id: "german/a1/vol3-grammar/adjectives-opposites", label: "3.19 Adjectives & Opposites" },
            { type: "doc", id: "german/a1/vol3-grammar/adverbs-of-time", label: "3.20 Adverbs of Time (Temporaladverbien)" },
            { type: "doc", id: "german/a1/vol3-grammar/welch-and-dies", label: "3.21 welch- and dies-" },
            { type: "doc", id: "german/a1/vol3-grammar/non-separable-verbs", label: "3.22 Non-Separable Verbs" },
          ],
        },
        {
          type: "category",
          label: "Volume 4: Home, City & Transport",
          items: [
            { type: "doc", id: "german/a1/vol4-home/apartment-rooms", label: "4.1 Apartment & Rooms" },
            { type: "doc", id: "german/a1/vol4-home/furniture-household", label: "4.2 Furniture & Household" },
            { type: "doc", id: "german/a1/vol4-home/apartment-problems", label: "4.3 Apartment Problems" },
            { type: "doc", id: "german/a1/vol4-home/hausmeister-neighbors", label: "4.4 Hausmeister & Neighbors" },
            { type: "doc", id: "german/a1/vol4-home/apartment-search", label: "4.5 Apartment Search" },
            { type: "doc", id: "german/a1/vol4-home/city-places", label: "4.6 City & Places" },
            { type: "doc", id: "german/a1/vol4-home/directions", label: "4.7 Directions" },
            { type: "doc", id: "german/a1/vol4-home/public-transport", label: "4.8 Public Transport" },
            { type: "doc", id: "german/a1/vol4-home/taxi-transport", label: "4.9 Taxi & Transport" },
          ],
        },
        {
          type: "category",
          label: "Volume 5: Shopping, Food & Money",
          items: [
            { type: "doc", id: "german/a1/vol5-shopping/supermarket", label: "5.1 The Supermarket" },
            { type: "doc", id: "german/a1/vol5-shopping/food-drinks", label: "5.2 Food & Drinks" },
            { type: "doc", id: "german/a1/vol5-shopping/quantities", label: "5.3 Quantities & Units" },
            { type: "doc", id: "german/a1/vol5-shopping/prices", label: "5.4 Prices & Costs" },
            { type: "doc", id: "german/a1/vol5-shopping/payment", label: "5.5 Payment (Bar & Karte)" },
            { type: "doc", id: "german/a1/vol5-shopping/bakery-cafe", label: "5.6 Bakery & Café" },
            { type: "doc", id: "german/a1/vol5-shopping/restaurant", label: "5.7 Restaurant & Ordering" },
            { type: "doc", id: "german/a1/vol5-shopping/clothing", label: "5.8 Clothing & Sizes" },
            { type: "doc", id: "german/a1/vol5-shopping/returns-complaints", label: "5.9 Returns & Complaints" },
          ],
        },
        {
          type: "category",
          label: "Volume 6: Work, School & Communication",
          items: [
            { type: "doc", id: "german/a1/vol6-work/profession-workplace", label: "6.1 Profession & Workplace" },
            { type: "doc", id: "german/a1/vol6-work/office-conversations", label: "6.2 Office Conversations" },
            { type: "doc", id: "german/a1/vol6-work/work-schedule-urlaub", label: "6.3 Work Schedule & Urlaub" },
            { type: "doc", id: "german/a1/vol6-work/school-language-course", label: "6.4 School & Language Course" },
            { type: "doc", id: "german/a1/vol6-work/kita-school", label: "6.5 Kita & School Basics" },
            { type: "doc", id: "german/a1/vol6-work/appointments", label: "6.6 Making Appointments" },
            { type: "doc", id: "german/a1/vol6-work/telephone", label: "6.7 Telephone German" },
            { type: "doc", id: "german/a1/vol6-work/email-messages", label: "6.8 Short Messages & Emails" },
            { type: "doc", id: "german/a1/vol6-work/invitations-plans", label: "6.9 Invitations & Plans" },
          ],
        },
        {
          type: "category",
          label: "Volume 7: Health, Services & Bureaucracy",
          items: [
            { type: "doc", id: "german/a1/vol7-health/body-symptoms", label: "7.1 Body & Symptoms" },
            { type: "doc", id: "german/a1/vol7-health/doctor", label: "7.2 Doctor Visit" },
            { type: "doc", id: "german/a1/vol7-health/pharmacy", label: "7.3 Pharmacy (Apotheke)" },
            { type: "doc", id: "german/a1/vol7-health/post-office", label: "7.4 Post Office" },
            { type: "doc", id: "german/a1/vol7-health/bank", label: "7.5 Bank Services" },
            { type: "doc", id: "german/a1/vol7-health/phone-internet-services", label: "7.6 Phone & Internet" },
            { type: "doc", id: "german/a1/vol7-health/buergeramt-rathaus", label: "7.7 Bürgeramt & Town Hall" },
            { type: "doc", id: "german/a1/vol7-health/anmeldung-forms", label: "7.8 Anmeldung & Forms" },
            { type: "doc", id: "german/a1/vol7-health/official-letters-notices", label: "7.9 Official Letters & Notices" },
          ],
        },
        {
          type: "category",
          label: "Volume 8: Leisure, Weather & Travel",
          items: [
            { type: "doc", id: "german/a1/vol8-leisure/weather", label: "8.1 Weather" },
            { type: "doc", id: "german/a1/vol8-leisure/seasons", label: "8.2 Seasons" },
            { type: "doc", id: "german/a1/vol8-leisure/sports", label: "8.3 Sports & Fitness" },
            { type: "doc", id: "german/a1/vol8-leisure/music-movies-books", label: "8.4 Music, Movies & Books" },
            { type: "doc", id: "german/a1/vol8-leisure/events-museum-cinema", label: "8.5 Events, Museum & Cinema" },
            { type: "doc", id: "german/a1/vol8-leisure/travel", label: "8.6 Travel & Vacation" },
            { type: "doc", id: "german/a1/vol8-leisure/hotel", label: "8.7 Hotel & Check-in" },
            { type: "doc", id: "german/a1/vol8-leisure/train-airport", label: "8.8 Train & Airport" },
            { type: "doc", id: "german/a1/vol8-leisure/german-everyday-culture", label: "8.9 German Everyday Culture" },
          ],
        },
        {
          type: "category",
          label: "Volume 9: Communication & Roleplay Lab",
          items: [
            { type: "doc", id: "german/a1/vol9-roleplay/ask-information", label: "9.1 Ask for Information" },
            { type: "doc", id: "german/a1/vol9-roleplay/give-information", label: "9.2 Give Information" },
            { type: "doc", id: "german/a1/vol9-roleplay/make-requests", label: "9.3 Make Requests" },
            { type: "doc", id: "german/a1/vol9-roleplay/respond-requests", label: "9.4 Respond to Requests" },
            { type: "doc", id: "german/a1/vol9-roleplay/ask-clarification", label: "9.5 Ask for Clarification" },
            { type: "doc", id: "german/a1/vol9-roleplay/ask-repeat", label: "9.6 Ask Someone to Repeat" },
            { type: "doc", id: "german/a1/vol9-roleplay/speak-slowly", label: "9.7 Ask to Speak Slowly" },
            { type: "doc", id: "german/a1/vol9-roleplay/apologize", label: "9.8 Apologize" },
            { type: "doc", id: "german/a1/vol9-roleplay/thank-someone", label: "9.9 Thank Someone" },
            { type: "doc", id: "german/a1/vol9-roleplay/agree-disagree", label: "9.10 Agree & Disagree" },
            { type: "doc", id: "german/a1/vol9-roleplay/invite-someone", label: "9.11 Invite Someone" },
            { type: "doc", id: "german/a1/vol9-roleplay/make-plans", label: "9.12 Make Plans" },
            { type: "doc", id: "german/a1/vol9-roleplay/complaints", label: "9.13 Complaints" },
            { type: "doc", id: "german/a1/vol9-roleplay/emergency-situations", label: "9.14 Emergency Situations" },
          ],
        },
        {
          type: "category",
          label: "Volume 10: Goethe & telc A1 Exam Center",
          items: [
            { type: "doc", id: "german/a1/exam-center/goethe-lesen", label: "10.1 Goethe A1: Lesen" },
            { type: "doc", id: "german/a1/exam-center/goethe-hoeren", label: "10.2 Goethe A1: Hören" },
            { type: "doc", id: "german/a1/exam-center/goethe-schreiben", label: "10.3 Goethe A1: Schreiben" },
            { type: "doc", id: "german/a1/exam-center/goethe-sprechen", label: "10.4 Goethe A1: Sprechen" },
            { type: "doc", id: "german/a1/exam-center/telc-overview", label: "10.5 telc Deutsch A1 Overview" },
            { type: "doc", id: "german/a1/exam-center/mock-exams", label: "10.6 Full Mock Exams" },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "GERMAN A2 - IN DEVELOPMENT",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Volume 1: A1 Revision & A2 Bridge",
          items: [
            { type: "doc", id: "german/a2/vol1-bridge/a1-grammar-check", label: "1.1 A1 Grammar Check" },
            { type: "doc", id: "german/a2/vol1-bridge/a1-vocabulary-check", label: "1.2 A1 Vocabulary Check" },
            { type: "doc", id: "german/a2/vol1-bridge/sentence-expansion", label: "1.3 Sentence Expansion" },
            { type: "doc", id: "german/a2/vol1-bridge/connecting-sentences", label: "1.4 Connecting Sentences" },
            { type: "doc", id: "german/a2/vol1-bridge/a2-communication-goals", label: "1.5 A2 Communication Goals" },
          ],
        },
        {
          type: "category",
          label: "Volume 2: Past, Experiences & Life Stories",
          items: [
            { type: "doc", id: "german/a2/vol2-past/perfekt", label: "2.1 Perfekt" },
            { type: "doc", id: "german/a2/vol2-past/common-irregular-participles", label: "2.2 Common Irregular Participles" },
            { type: "doc", id: "german/a2/vol2-past/praeteritum-sein-haben-modals", label: "2.3 Präteritum: sein, haben & Modals" },
            { type: "doc", id: "german/a2/vol2-past/yesterday", label: "2.4 Yesterday" },
            { type: "doc", id: "german/a2/vol2-past/last-weekend", label: "2.5 Last Weekend" },
            { type: "doc", id: "german/a2/vol2-past/holidays", label: "2.6 Holidays & Trips" },
            { type: "doc", id: "german/a2/vol2-past/earlier-life", label: "2.7 Earlier Life" },
            { type: "doc", id: "german/a2/vol2-past/experiences", label: "2.8 Experiences" },
            { type: "doc", id: "german/a2/vol2-past/storytelling", label: "2.9 Storytelling" },
            { type: "doc", id: "german/a2/vol2-past/sequencing-events", label: "2.10 Sequencing Events" },
          ],
        },
        {
          type: "category",
          label: "Volume 3: Grammar & Sentence Builder",
          items: [
            { type: "doc", id: "german/a2/vol3-grammar/sentence-structure", label: "3.1 Sentence Structure" },
            { type: "doc", id: "german/a2/vol3-grammar/main-clause-connectors", label: "3.2 Main-Clause Connectors" },
            { type: "doc", id: "german/a2/vol3-grammar/subordinate-clauses", label: "3.3 Subordinate Clauses (weil, dass, wenn)" },
            { type: "doc", id: "german/a2/vol3-grammar/verb-position-nebensaetze", label: "3.4 Verb Position in Nebensätze" },
            { type: "doc", id: "german/a2/vol3-grammar/perfekt-review", label: "3.5 Perfekt Review" },
            { type: "doc", id: "german/a2/vol3-grammar/praeteritum-review", label: "3.6 Präteritum Review" },
            { type: "doc", id: "german/a2/vol3-grammar/reflexive-verbs", label: "3.7 Reflexive Verbs" },
            { type: "doc", id: "german/a2/vol3-grammar/adjectives", label: "3.8 Adjectives" },
            { type: "doc", id: "german/a2/vol3-grammar/comparatives", label: "3.9 Comparatives" },
            { type: "doc", id: "german/a2/vol3-grammar/superlatives", label: "3.10 Superlatives" },
            { type: "doc", id: "german/a2/vol3-grammar/adverbs", label: "3.11 Adverbs" },
            { type: "doc", id: "german/a2/vol3-grammar/prepositions-advanced", label: "3.12 Prepositions" },
            { type: "doc", id: "german/a2/vol3-grammar/wechselpraepositionen", label: "3.13 Wechselpräpositionen" },
            { type: "doc", id: "german/a2/vol3-grammar/verbs-with-prepositions", label: "3.14 Verbs with Prepositions" },
            { type: "doc", id: "german/a2/vol3-grammar/indefinite-pronouns", label: "3.15 Indefinite Pronouns" },
            { type: "doc", id: "german/a2/vol3-grammar/pronouns-review", label: "3.16 Pronouns Review" },
            { type: "doc", id: "german/a2/vol3-grammar/imperative-expanded", label: "3.17 Imperative" },
            { type: "doc", id: "german/a2/vol3-grammar/infinitive-mit-zu", label: "3.18 Infinitive mit zu" },
            { type: "doc", id: "german/a2/vol3-grammar/polite-requests-wishes", label: "3.19 Polite Requests (Konjunktiv II)" },
            { type: "doc", id: "german/a2/vol3-grammar/future-plans", label: "3.20 Future & Plans" },
          ],
        },
        {
          type: "category",
          label: "Volume 4: Home, City & Everyday Problems",
          items: [
            { type: "doc", id: "german/a2/vol4-home/home-review", label: "4.1 Home Review" },
            { type: "doc", id: "german/a2/vol4-home/apartment-problems", label: "4.2 Apartment Problems" },
            { type: "doc", id: "german/a2/vol4-home/hausmeister", label: "4.3 Hausmeister" },
            { type: "doc", id: "german/a2/vol4-home/landlord-hausverwaltung", label: "4.4 Landlord & Hausverwaltung" },
            { type: "doc", id: "german/a2/vol4-home/repairs", label: "4.5 Repairs" },
            { type: "doc", id: "german/a2/vol4-home/apartment-search-advanced", label: "4.6 Apartment Search" },
            { type: "doc", id: "german/a2/vol4-home/neighborhood", label: "4.7 Neighborhood" },
            { type: "doc", id: "german/a2/vol4-home/city-services", label: "4.8 City Services" },
            { type: "doc", id: "german/a2/vol4-home/transport-problems", label: "4.9 Transport Problems" },
            { type: "doc", id: "german/a2/vol4-home/delays-alternatives", label: "4.10 Delays & Alternatives" },
          ],
        },
        {
          type: "category",
          label: "Volume 5: Shopping, Services & Money",
          items: [
            { type: "doc", id: "german/a2/vol5-shopping/shopping-review", label: "5.1 Shopping Review" },
            { type: "doc", id: "german/a2/vol5-shopping/product-comparison", label: "5.2 Product Comparison" },
            { type: "doc", id: "german/a2/vol5-shopping/household-electronics", label: "5.3 Household & Electronics" },
            { type: "doc", id: "german/a2/vol5-shopping/customer-service", label: "5.4 Customer Service" },
            { type: "doc", id: "german/a2/vol5-shopping/returns", label: "5.5 Returns" },
            { type: "doc", id: "german/a2/vol5-shopping/complaints", label: "5.6 Complaints" },
            { type: "doc", id: "german/a2/vol5-shopping/online-shopping", label: "5.7 Online Shopping" },
            { type: "doc", id: "german/a2/vol5-shopping/delivery-problems", label: "5.8 Delivery Problems" },
            { type: "doc", id: "german/a2/vol5-shopping/bank-payment", label: "5.9 Bank & Payment" },
            { type: "doc", id: "german/a2/vol5-shopping/bills", label: "5.10 Bills & Invoices" },
            { type: "doc", id: "german/a2/vol5-shopping/contracts-subscriptions", label: "5.11 Contracts & Subscriptions" },
            { type: "doc", id: "german/a2/vol5-shopping/negotiating-solutions", label: "5.12 Negotiating Solutions" },
          ],
        },
        {
          type: "category",
          label: "Volume 6: Work, Education & Communication",
          items: [
            { type: "doc", id: "german/a2/vol6-work/job-profession", label: "6.1 Job & Profession" },
            { type: "doc", id: "german/a2/vol6-work/describing-your-job", label: "6.2 Describing Your Job" },
            { type: "doc", id: "german/a2/vol6-work/working-day", label: "6.3 Working Day" },
            { type: "doc", id: "german/a2/vol6-work/responsibilities", label: "6.4 Responsibilities" },
            { type: "doc", id: "german/a2/vol6-work/colleagues", label: "6.5 Colleagues" },
            { type: "doc", id: "german/a2/vol6-work/workplace-problems", label: "6.6 Workplace Problems" },
            { type: "doc", id: "german/a2/vol6-work/meetings", label: "6.7 Meetings" },
            { type: "doc", id: "german/a2/vol6-work/appointments-advanced", label: "6.8 Appointments" },
            { type: "doc", id: "german/a2/vol6-work/urlaub-krankmeldung", label: "6.9 Urlaub & Krankmeldung" },
            { type: "doc", id: "german/a2/vol6-work/workplace-emails", label: "6.10 Workplace Emails" },
            { type: "doc", id: "german/a2/vol6-work/education-courses", label: "6.11 Education & Courses" },
            { type: "doc", id: "german/a2/vol6-work/exams", label: "6.12 Exams" },
            { type: "doc", id: "german/a2/vol6-work/career-future-plans", label: "6.13 Career & Future Plans" },
            { type: "doc", id: "german/a2/vol6-work/job-advertisements", label: "6.14 Job Advertisements" },
          ],
        },
        {
          type: "category",
          label: "Volume 7: Health, Family & Relationships",
          items: [
            { type: "doc", id: "german/a2/vol7-health/health-review", label: "7.1 Health Review" },
            { type: "doc", id: "german/a2/vol7-health/symptoms-detailed", label: "7.2 Symptoms Detailed" },
            { type: "doc", id: "german/a2/vol7-health/duration-seit-vor", label: "7.3 Duration (seit / vor)" },
            { type: "doc", id: "german/a2/vol7-health/doctor-instructions", label: "7.4 Doctor Instructions" },
            { type: "doc", id: "german/a2/vol7-health/pharmacy-advanced", label: "7.5 Pharmacy" },
            { type: "doc", id: "german/a2/vol7-health/family-dynamics", label: "7.6 Family Dynamics" },
            { type: "doc", id: "german/a2/vol7-health/kita-school", label: "7.7 Kita & School" },
            { type: "doc", id: "german/a2/vol7-health/social-life", label: "7.8 Social Life" },
            { type: "doc", id: "german/a2/vol7-health/invitations-advanced", label: "7.9 Invitations" },
            { type: "doc", id: "german/a2/vol7-health/feelings", label: "7.10 Feelings & Emotions" },
            { type: "doc", id: "german/a2/vol7-health/giving-advice", label: "7.11 Giving Advice" },
            { type: "doc", id: "german/a2/vol7-health/everyday-problems", label: "7.12 Everyday Problems" },
          ],
        },
        {
          type: "category",
          label: "Volume 8: Travel, Leisure, Weather & Events",
          items: [
            { type: "doc", id: "german/a2/vol8-leisure/travel-planning-advanced", label: "8.1 Travel Planning" },
            { type: "doc", id: "german/a2/vol8-leisure/booking", label: "8.2 Booking" },
            { type: "doc", id: "german/a2/vol8-leisure/train-flight-problems", label: "8.3 Train & Flight Problems" },
            { type: "doc", id: "german/a2/vol8-leisure/hotel-problems", label: "8.4 Hotel Problems" },
            { type: "doc", id: "german/a2/vol8-leisure/weather-advanced", label: "8.5 Weather" },
            { type: "doc", id: "german/a2/vol8-leisure/weather-plans", label: "8.6 Weather & Plans" },
            { type: "doc", id: "german/a2/vol8-leisure/sports-advanced", label: "8.7 Sports" },
            { type: "doc", id: "german/a2/vol8-leisure/music-films-books", label: "8.8 Music, Films & Books" },
            { type: "doc", id: "german/a2/vol8-leisure/events", label: "8.9 Events" },
            { type: "doc", id: "german/a2/vol8-leisure/invitations-planning", label: "8.10 Invitations" },
            { type: "doc", id: "german/a2/vol8-leisure/making-plans", label: "8.11 Making Plans" },
            { type: "doc", id: "german/a2/vol8-leisure/changing-plans", label: "8.12 Changing Plans" },
            { type: "doc", id: "german/a2/vol8-leisure/comparing-options", label: "8.13 Comparing Options" },
            { type: "doc", id: "german/a2/vol8-leisure/describing-experiences", label: "8.14 Describing Experiences" },
          ],
        },
        {
          type: "category",
          label: "Volume 9: Communication & Roleplay Lab",
          items: [
            { type: "doc", id: "german/a2/vol9-roleplay/asking-information", label: "9.1 Ask for Information" },
            { type: "doc", id: "german/a2/vol9-roleplay/explaining", label: "9.2 Explaining" },
            { type: "doc", id: "german/a2/vol9-roleplay/giving-reasons", label: "9.3 Giving Reasons" },
            { type: "doc", id: "german/a2/vol9-roleplay/opinions", label: "9.4 Opinions" },
            { type: "doc", id: "german/a2/vol9-roleplay/agreeing-disagreeing", label: "9.5 Agreeing & Disagreeing" },
            { type: "doc", id: "german/a2/vol9-roleplay/comparing-opinions", label: "9.6 Comparing" },
            { type: "doc", id: "german/a2/vol9-roleplay/suggestions", label: "9.7 Suggestions" },
            { type: "doc", id: "german/a2/vol9-roleplay/accepting-rejecting", label: "9.8 Accepting & Rejecting" },
            { type: "doc", id: "german/a2/vol9-roleplay/planning", label: "9.9 Planning" },
            { type: "doc", id: "german/a2/vol9-roleplay/negotiating", label: "9.10 Negotiating" },
            { type: "doc", id: "german/a2/vol9-roleplay/advice", label: "9.11 Advice" },
            { type: "doc", id: "german/a2/vol9-roleplay/complaints", label: "9.12 Complaints" },
            { type: "doc", id: "german/a2/vol9-roleplay/clarification", label: "9.13 Clarification" },
            { type: "doc", id: "german/a2/vol9-roleplay/conversation-repair", label: "9.14 Conversation Repair" },
            { type: "doc", id: "german/a2/vol9-roleplay/ai-roleplays-advanced", label: "9.15 AI Roleplays" },
          ],
        },
        {
          type: "category",
          label: "Volume 10: Goethe & telc A2 Exam Center",
          items: [
            { type: "doc", id: "german/a2/vol10-exam/goethe-a2-overview", label: "10.1 Goethe A2 Overview" },
            { type: "doc", id: "german/a2/vol10-exam/goethe-reading", label: "10.2 Goethe Reading" },
            { type: "doc", id: "german/a2/vol10-exam/goethe-listening", label: "10.3 Goethe Listening" },
            { type: "doc", id: "german/a2/vol10-exam/goethe-writing", label: "10.4 Goethe Writing" },
            { type: "doc", id: "german/a2/vol10-exam/goethe-speaking", label: "10.5 Goethe Speaking" },
            { type: "doc", id: "german/a2/vol10-exam/telc-a2-overview", label: "10.6 telc A2 Overview" },
            { type: "doc", id: "german/a2/vol10-exam/telc-reading", label: "10.7 telc Reading" },
            { type: "doc", id: "german/a2/vol10-exam/telc-listening", label: "10.8 telc Listening" },
            { type: "doc", id: "german/a2/vol10-exam/telc-language-elements", label: "10.9 telc Language Elements" },
            { type: "doc", id: "german/a2/vol10-exam/telc-writing", label: "10.10 telc Writing" },
            { type: "doc", id: "german/a2/vol10-exam/telc-speaking", label: "10.11 telc Speaking" },
            { type: "doc", id: "german/a2/vol10-exam/mock-exams", label: "10.12 Full Mock Exams" },
            { type: "doc", id: "german/a2/vol10-exam/error-analysis", label: "10.13 Error Analysis" },
            { type: "doc", id: "german/a2/vol10-exam/weakness-based-revision", label: "10.14 Weakness-Based Revision" },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "GERMAN B1 - FIRST CHAPTERS",
      collapsed: true,
      items: [
        { type: "doc", id: "german/b1/start-here", label: "B1: Start Here" },
        {
          type: "category",
          label: "B1 Grammar",
          items: [
            { type: "doc", id: "german/b1/grammar/purpose-clauses", label: "B1.1 um … zu / damit / ohne … zu" },
            { type: "doc", id: "german/b1/grammar/konjunktiv-ii", label: "B1.2 Konjunktiv II" },
            { type: "doc", id: "german/b1/grammar/da-wo-compounds", label: "B1.3 da- & wo-Compounds" },
          ],
        },
        {
          type: "category",
          label: "B1 Exam",
          items: [
            { type: "doc", id: "german/b1/exam/b1-writing", label: "B1 Writing: Three Tasks" },
            { type: "doc", id: "german/b1/exam/b1-speaking", label: "B1 Speaking: Plan, Present, Discuss" },
            { type: "doc", id: "german/b1/exam/b1-repair-bank", label: "B1 Repair Bank" },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "PARALLEL LEARNING SYSTEMS",
      items: [
        { type: "doc", id: "german/parallel-systems/vocabulary-vault", label: "A. Vocabulary Vault" },
        { type: "doc", id: "german/parallel-systems/grammar-reference", label: "B. Grammar Reference" },
        { type: "doc", id: "german/parallel-systems/redemittel-phrases", label: "C. Redemittel & Useful Phrases" },
        { type: "doc", id: "german/parallel-systems/pronunciation-coach", label: "D. Pronunciation Coach" },
        { type: "doc", id: "german/parallel-systems/reading-practice", label: "E. Reading Practice" },
        { type: "doc", id: "german/parallel-systems/listening-practice", label: "F. Listening Practice" },
        { type: "doc", id: "german/parallel-systems/writing-practice", label: "G. Writing Practice" },
        { type: "doc", id: "german/parallel-systems/speaking-practice", label: "H. Speaking Practice" },
        { type: "doc", id: "german/parallel-systems/ai-roleplay", label: "I. AI Roleplay Lab" },
        { type: "doc", id: "german/parallel-systems/flashcards", label: "J. Flashcards & Spaced Repetition" },
        { type: "doc", id: "german/parallel-systems/progress-dashboard", label: "K. Mistake Log & Repair" },
      ],
    },
  ],
  englishSidebar: [
    {
      type: "category",
      label: "A1-A2 Beginner Foundations",
      collapsed: false,
      items: [
        { type: "doc", id: "english/a1-a2-foundations/b01-sound-pronunciation-core", label: "1.1 Sound Pronunciation Core" },
        { type: "doc", id: "english/a1-a2-foundations/b02-classroom-and-learning-language", label: "1.2 Classroom and Learning Language" },
        { type: "doc", id: "english/a1-a2-foundations/b03-be-verbs-and-identity", label: "1.3 Be Verbs and Identity" },
        { type: "doc", id: "english/a1-a2-foundations/b04-basic-sentence-order", label: "1.4 Basic Sentence Order" },
        { type: "doc", id: "english/a1-a2-foundations/b05-present-simple-daily-life", label: "1.5 Present Simple Daily Life" },
        { type: "doc", id: "english/a1-a2-foundations/b06-present-continuous", label: "1.6 Present Continuous" },
        { type: "doc", id: "english/a1-a2-foundations/b07-nouns-articles-quantity", label: "1.7 Nouns Articles Quantity" },
        { type: "doc", id: "english/a1-a2-foundations/b08-basic-prepositions", label: "1.8 Basic Prepositions" },
        { type: "doc", id: "english/a1-a2-foundations/b09-past-tense-pilot", label: "1.9 Past Tense Pilot" },
        { type: "doc", id: "english/a1-a2-foundations/b10-future-basics", label: "1.10 Future Basics" },
        { type: "doc", id: "english/a1-a2-foundations/b11-everyday-functions", label: "1.11 Everyday Functions" },
        { type: "doc", id: "english/a1-a2-foundations/b12-beginner-fluency", label: "1.12 Beginner Fluency" },
      ],
    },
    {
      type: "category",
      label: "B1-B2 Confident Communication",
      collapsed: false,
      items: [
        { type: "doc", id: "english/b1-b2-confident-communication/i01-tense-control", label: "2.1 Tense Control" },
        { type: "doc", id: "english/b1-b2-confident-communication/i02-questions-and-interaction", label: "2.2 Questions and Interaction" },
        { type: "doc", id: "english/b1-b2-confident-communication/i03-sentence-expansion", label: "2.3 Sentence Expansion" },
        { type: "doc", id: "english/b1-b2-confident-communication/i04-articles-determiners-precision", label: "2.4 Articles Determiners Precision" },
        { type: "doc", id: "english/b1-b2-confident-communication/i05-preposition-patterns", label: "2.5 Preposition Patterns" },
        { type: "doc", id: "english/b1-b2-confident-communication/i06-modals-and-obligation", label: "2.6 Modals and Obligation" },
        { type: "doc", id: "english/b1-b2-confident-communication/i07-workplace-english", label: "2.7 Workplace English" },
        { type: "doc", id: "english/b1-b2-confident-communication/i08-real-life-roleplay", label: "2.8 Real Life Roleplay" },
        { type: "doc", id: "english/b1-b2-confident-communication/i09-storytelling-and-fluency", label: "2.9 Storytelling and Fluency" },
        { type: "doc", id: "english/b1-b2-confident-communication/i10-opinions-discussion", label: "2.10 Opinions Discussion" },
        { type: "doc", id: "english/b1-b2-confident-communication/i11-vocabulary-collocations", label: "2.11 Vocabulary Collocations" },
        { type: "doc", id: "english/b1-b2-confident-communication/i12-intermediate-review", label: "2.12 Intermediate Review" },
      ],
    },
    {
      type: "category",
      label: "B2-C1 Professional Fluency",
      collapsed: false,
      items: [
        { type: "doc", id: "english/b2-c1-professional-fluency/a01-advanced-grammar-precision", label: "3.1 Advanced Grammar Precision" },
        { type: "doc", id: "english/b2-c1-professional-fluency/a02-professional-register", label: "3.2 Professional Register" },
        { type: "doc", id: "english/b2-c1-professional-fluency/a03-technical-communication", label: "3.3 Technical Communication" },
        { type: "doc", id: "english/b2-c1-professional-fluency/a04-meeting-and-discussion-skills", label: "3.4 Meeting and Discussion Skills" },
        { type: "doc", id: "english/b2-c1-professional-fluency/a05-advanced-fluency", label: "3.5 Advanced Fluency" },
        { type: "doc", id: "english/b2-c1-professional-fluency/a06-nuance-and-vocabulary", label: "3.6 Nuance and Vocabulary" },
        { type: "doc", id: "english/b2-c1-professional-fluency/a07-presentations-and-storytelling", label: "3.7 Presentations and Storytelling" },
        { type: "doc", id: "english/b2-c1-professional-fluency/a08-interview-speaking", label: "3.8 Interview Speaking" },
        { type: "doc", id: "english/b2-c1-professional-fluency/a09-negotiation-and-influence", label: "3.9 Negotiation and Influence" },
        { type: "doc", id: "english/b2-c1-professional-fluency/a10-cultural-and-social-fluency", label: "3.10 Cultural and Social Fluency" },
        { type: "doc", id: "english/b2-c1-professional-fluency/a11-advanced-pronunciation", label: "3.11 Advanced Pronunciation" },
        { type: "doc", id: "english/b2-c1-professional-fluency/a12-mastery-review", label: "3.12 Mastery Review" },
      ],
    },
  ],
};

export default sidebars;
