import type {SidebarsConfig} from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  germanSidebar: [
    {
      type: "category",
      label: "START HERE: COURSE GUIDE",
      collapsed: false,
      items: [
        { type: "doc", id: "german/course-guide/how-this-course-works", label: "How This Course Works" },
        { type: "doc", id: "german/course-guide/learning-path", label: "Recommended Learning Path" },
      ],
    },
    {
      type: "category",
      label: "GERMAN A1 - COMPLETE BEGINNER",
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Volume 1: Foundations",
          items: [
            { type: "doc", id: "german/a1/vol1-foundations/survival-kit", label: "1.0 Survival Kit: First 30 Sentences" },
            { type: "doc", id: "german/a1/vol1-foundations/alphabet-pronunciation", label: "1.1 Alphabet & Pronunciation" },
            { type: "doc", id: "german/a1/vol1-foundations/reading-compound-words", label: "1.2 Reading German Words & Compound Nouns" },
            { type: "doc", id: "german/a1/vol1-foundations/greetings-basic-comm", label: "1.3 Greetings & Basic Communication" },
            { type: "doc", id: "german/a1/vol1-foundations/personal-pronouns", label: "1.4 Personal Pronouns & Du vs. Sie" },
            { type: "doc", id: "german/a1/vol1-foundations/numbers-dates-time", label: "1.5 Numbers, Dates & Time" },
            { type: "doc", id: "german/a1/vol1-foundations/first-sentences", label: "1.6 First Sentences & Introductions" },
            { type: "doc", id: "german/a1/vol1-foundations/ordinal-numbers", label: "1.7 Numbers above 100, Ordinals & Dates" },
          ],
        },
        {
          type: "category",
          label: "Volume 2: People & Everyday Life",
          items: [
            { type: "doc", id: "german/a1/vol2-people/personal-information", label: "2.1 Asking for Personal Information" },
            { type: "doc", id: "german/a1/vol2-people/family", label: "2.2 Family & Possessives" },
            { type: "doc", id: "german/a1/vol2-people/describing-people", label: "2.3 Describing People" },
            { type: "doc", id: "german/a1/vol2-people/daily-routine", label: "2.4 Daily Routine & Separable Verbs" },
            { type: "doc", id: "german/a1/vol2-people/hobbies-free-time", label: "2.5 Hobbies & Free Time" },
            { type: "doc", id: "german/a1/vol2-people/likes-preferences", label: "2.6 Likes & Preferences" },
          ],
        },
        {
          type: "category",
          label: "Volume 3: Grammar & Sentence Builder",
          items: [
            { type: "doc", id: "german/a1/vol3-grammar/nouns-gender", label: "3.1 Nouns & Gender" },
            { type: "doc", id: "german/a1/vol3-grammar/plurals", label: "3.2 Plurals (Der Plural)" },
            { type: "doc", id: "german/a1/vol3-grammar/nominative", label: "3.3 Nominative Case" },
            { type: "doc", id: "german/a1/vol3-grammar/present-tense-verbs", label: "3.4 Present Tense Verbs" },
            { type: "doc", id: "german/a1/vol3-grammar/sein-and-haben", label: "3.5 sein & haben" },
            { type: "doc", id: "german/a1/vol3-grammar/modal-verbs", label: "3.6 Modal Verbs" },
            { type: "doc", id: "german/a1/vol3-grammar/sentence-structure-v2", label: "3.7 Sentence Structure & V2 Rule" },
            { type: "doc", id: "german/a1/vol3-grammar/questions", label: "3.8 Questions (W-Fragen & Ja/Nein)" },
            { type: "doc", id: "german/a1/vol3-grammar/accusative", label: "3.9 Accusative Case (Direct Object)" },
            { type: "doc", id: "german/a1/vol3-grammar/dative", label: "3.10 Dative Case (Indirect Object)" },
            { type: "doc", id: "german/a1/vol3-grammar/negation", label: "3.11 Negation (nicht vs. kein)" },
            { type: "doc", id: "german/a1/vol3-grammar/separable-verbs", label: "3.12 Separable Verbs" },
            { type: "doc", id: "german/a1/vol3-grammar/prepositions", label: "3.13 Basic Prepositions" },
            { type: "doc", id: "german/a1/vol3-grammar/conjunctions", label: "3.14 Conjunctions (und, oder, aber, denn)" },
            { type: "doc", id: "german/a1/vol3-grammar/imperative", label: "3.15 Imperative (Commands)" },
            { type: "doc", id: "german/a1/vol3-grammar/basic-past", label: "3.16 Basic Past (war & hatte)" },
            { type: "doc", id: "german/a1/vol3-grammar/polite-requests", label: "3.17 Polite Requests (Ich möchte / hätte gern)" },
            { type: "doc", id: "german/a1/vol3-grammar/perfekt-spoken-past", label: "3.18 Perfekt (Spoken Past)" },
            { type: "doc", id: "german/a1/vol3-grammar/adjectives-opposites", label: "3.19 Adjectives & Opposites" },
            { type: "doc", id: "german/a1/vol3-grammar/adverbs-of-time", label: "3.20 Adverbs of Time (Temporaladverbien)" },
            { type: "doc", id: "german/a1/vol3-grammar/welch-and-dies", label: "3.21 welch- and dies-" },
            { type: "doc", id: "german/a1/vol3-grammar/non-separable-verbs", label: "3.22 Non-Separable Verbs" },
          ],
        },
        {
          type: "category",
          label: "Volume 4: Home, City & Transport",
          items: [
            { type: "doc", id: "german/a1/vol4-home/apartment-rooms", label: "4.1 Apartment & Rooms" },
            { type: "doc", id: "german/a1/vol4-home/furniture-household", label: "4.2 Furniture & Household" },
            { type: "doc", id: "german/a1/vol4-home/apartment-problems", label: "4.3 Apartment Problems" },
            { type: "doc", id: "german/a1/vol4-home/hausmeister-neighbors", label: "4.4 Hausmeister & Neighbors" },
            { type: "doc", id: "german/a1/vol4-home/apartment-search", label: "4.5 Apartment Search" },
            { type: "doc", id: "german/a1/vol4-home/city-places", label: "4.6 City & Places" },
            { type: "doc", id: "german/a1/vol4-home/directions", label: "4.7 Directions" },
            { type: "doc", id: "german/a1/vol4-home/public-transport", label: "4.8 Public Transport" },
            { type: "doc", id: "german/a1/vol4-home/taxi-transport", label: "4.9 Taxi & Transport" },
          ],
        },
        {
          type: "category",
          label: "Volume 5: Shopping, Food & Money",
          items: [
            { type: "doc", id: "german/a1/vol5-shopping/supermarket", label: "5.1 The Supermarket" },
            { type: "doc", id: "german/a1/vol5-shopping/food-drinks", label: "5.2 Food & Drinks" },
            { type: "doc", id: "german/a1/vol5-shopping/quantities", label: "5.3 Quantities & Units" },
            { type: "doc", id: "german/a1/vol5-shopping/prices", label: "5.4 Prices & Costs" },
            { type: "doc", id: "german/a1/vol5-shopping/payment", label: "5.5 Payment (Bar & Karte)" },
            { type: "doc", id: "german/a1/vol5-shopping/bakery-cafe", label: "5.6 Bakery & Café" },
            { type: "doc", id: "german/a1/vol5-shopping/restaurant", label: "5.7 Restaurant & Ordering" },
            { type: "doc", id: "german/a1/vol5-shopping/clothing", label: "5.8 Clothing & Sizes" },
            { type: "doc", id: "german/a1/vol5-shopping/returns-complaints", label: "5.9 Returns & Complaints" },
          ],
        },
        {
          type: "category",
          label: "Volume 6: Work, School & Communication",
          items: [
            { type: "doc", id: "german/a1/vol6-work/profession-workplace", label: "6.1 Profession & Workplace" },
            { type: "doc", id: "german/a1/vol6-work/office-conversations", label: "6.2 Office Conversations" },
            { type: "doc", id: "german/a1/vol6-work/work-schedule-urlaub", label: "6.3 Work Schedule & Urlaub" },
            { type: "doc", id: "german/a1/vol6-work/school-language-course", label: "6.4 School & Language Course" },
            { type: "doc", id: "german/a1/vol6-work/kita-school", label: "6.5 Kita & School Basics" },
            { type: "doc", id: "german/a1/vol6-work/appointments", label: "6.6 Making Appointments" },
            { type: "doc", id: "german/a1/vol6-work/telephone", label: "6.7 Telephone German" },
            { type: "doc", id: "german/a1/vol6-work/email-messages", label: "6.8 Short Messages & Emails" },
            { type: "doc", id: "german/a1/vol6-work/invitations-plans", label: "6.9 Invitations & Plans" },
          ],
        },
        {
          type: "category",
          label: "Volume 7: Health, Services & Bureaucracy",
          items: [
            { type: "doc", id: "german/a1/vol7-health/body-symptoms", label: "7.1 Body & Symptoms" },
            { type: "doc", id: "german/a1/vol7-health/doctor", label: "7.2 Doctor Visit" },
            { type: "doc", id: "german/a1/vol7-health/pharmacy", label: "7.3 Pharmacy (Apotheke)" },
            { type: "doc", id: "german/a1/vol7-health/post-office", label: "7.4 Post Office" },
            { type: "doc", id: "german/a1/vol7-health/bank", label: "7.5 Bank Services" },
            { type: "doc", id: "german/a1/vol7-health/phone-internet-services", label: "7.6 Phone & Internet" },
            { type: "doc", id: "german/a1/vol7-health/buergeramt-rathaus", label: "7.7 Bürgeramt & Town Hall" },
            { type: "doc", id: "german/a1/vol7-health/anmeldung-forms", label: "7.8 Anmeldung & Forms" },
            { type: "doc", id: "german/a1/vol7-health/official-letters-notices", label: "7.9 Official Letters & Notices" },
          ],
        },
        {
          type: "category",
          label: "Volume 8: Leisure, Weather & Travel",
          items: [
            { type: "doc", id: "german/a1/vol8-leisure/weather", label: "8.1 Weather" },
            { type: "doc", id: "german/a1/vol8-leisure/seasons", label: "8.2 Seasons" },
            { type: "doc", id: "german/a1/vol8-leisure/sports", label: "8.3 Sports & Fitness" },
            { type: "doc", id: "german/a1/vol8-leisure/music-movies-books", label: "8.4 Music, Movies & Books" },
            { type: "doc", id: "german/a1/vol8-leisure/events-museum-cinema", label: "8.5 Events, Museum & Cinema" },
            { type: "doc", id: "german/a1/vol8-leisure/travel", label: "8.6 Travel & Vacation" },
            { type: "doc", id: "german/a1/vol8-leisure/hotel", label: "8.7 Hotel & Check-in" },
            { type: "doc", id: "german/a1/vol8-leisure/train-airport", label: "8.8 Train & Airport" },
            { type: "doc", id: "german/a1/vol8-leisure/german-everyday-culture", label: "8.9 German Everyday Culture" },
          ],
        },
        {
          type: "category",
          label: "Volume 9: Communication & Roleplay Lab",
          items: [
            { type: "doc", id: "german/a1/vol9-roleplay/ask-information", label: "9.1 Ask for Information" },
            { type: "doc", id: "german/a1/vol9-roleplay/give-information", label: "9.2 Give Information" },
            { type: "doc", id: "german/a1/vol9-roleplay/make-requests", label: "9.3 Make Requests" },
            { type: "doc", id: "german/a1/vol9-roleplay/respond-requests", label: "9.4 Respond to Requests" },
            { type: "doc", id: "german/a1/vol9-roleplay/ask-clarification", label: "9.5 Ask for Clarification" },
            { type: "doc", id: "german/a1/vol9-roleplay/ask-repeat", label: "9.6 Ask Someone to Repeat" },
            { type: "doc", id: "german/a1/vol9-roleplay/speak-slowly", label: "9.7 Ask to Speak Slowly" },
            { type: "doc", id: "german/a1/vol9-roleplay/apologize", label: "9.8 Apologize" },
            { type: "doc", id: "german/a1/vol9-roleplay/thank-someone", label: "9.9 Thank Someone" },
            { type: "doc", id: "german/a1/vol9-roleplay/agree-disagree", label: "9.10 Agree & Disagree" },
            { type: "doc", id: "german/a1/vol9-roleplay/invite-someone", label: "9.11 Invite Someone" },
            { type: "doc", id: "german/a1/vol9-roleplay/make-plans", label: "9.12 Make Plans" },
            { type: "doc", id: "german/a1/vol9-roleplay/complaints", label: "9.13 Complaints" },
            { type: "doc", id: "german/a1/vol9-roleplay/emergency-situations", label: "9.14 Emergency Situations" },
          ],
        },
        {
          type: "category",
          label: "Volume 10: Goethe & telc A1 Exam Center",
          items: [
            { type: "doc", id: "german/a1/exam-center/goethe-lesen", label: "10.1 Goethe A1: Lesen" },
            { type: "doc", id: "german/a1/exam-center/goethe-hoeren", label: "10.2 Goethe A1: Hören" },
            { type: "doc", id: "german/a1/exam-center/goethe-schreiben", label: "10.3 Goethe A1: Schreiben" },
            { type: "doc", id: "german/a1/exam-center/goethe-sprechen", label: "10.4 Goethe A1: Sprechen" },
            { type: "doc", id: "german/a1/exam-center/telc-overview", label: "10.5 telc Deutsch A1 Overview" },
            { type: "doc", id: "german/a1/exam-center/mock-exams", label: "10.6 Full Mock Exams" },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "PARALLEL LEARNING SYSTEMS",
      items: [
        { type: "doc", id: "german/parallel-systems/vocabulary-vault", label: "A. Vocabulary Vault" },
        { type: "doc", id: "german/parallel-systems/grammar-reference", label: "B. Grammar Reference" },
        { type: "doc", id: "german/parallel-systems/redemittel-phrases", label: "C. Redemittel & Useful Phrases" },
        { type: "doc", id: "german/parallel-systems/pronunciation-coach", label: "D. Pronunciation Coach" },
        { type: "doc", id: "german/parallel-systems/reading-practice", label: "E. Reading Practice" },
        { type: "doc", id: "german/parallel-systems/listening-practice", label: "F. Listening Practice" },
        { type: "doc", id: "german/parallel-systems/writing-practice", label: "G. Writing Practice" },
        { type: "doc", id: "german/parallel-systems/speaking-practice", label: "H. Speaking Practice" },
        { type: "doc", id: "german/parallel-systems/ai-roleplay", label: "I. AI Roleplay Lab" },
        { type: "doc", id: "german/parallel-systems/flashcards", label: "J. Flashcards & Spaced Repetition" },
        { type: "doc", id: "german/parallel-systems/progress-dashboard", label: "K. Mistake Log & Repair" },
      ],
    },
  ],
};

export default sidebars;
