export interface GermanB1TopicCatalogItem {
  lessonNo: number;
  id: string;
  titleEn: string;
  titleDe: string;
  plainLanguageHook: string;
  pathGroup: "grammar" | "exam" | "survival" | "vocabulary";
  coreContent: string[];
  goetheB1Vocabulary: string[];
  examRelevance: string;
  dailyLifeExtension: string[];
  commonMistakes: string[];
  priority: "low" | "medium" | "high";
}

export const germanB1TopicCatalog: GermanB1TopicCatalogItem[] = [
  {
    lessonNo: 1,
    id: "b1-catalog-reflexive-verbs-1",
    titleEn: "Reflexive Verbs Part 1",
    titleDe: "Reflexivverben Teil 1",
    plainLanguageHook: "Some German verbs need a self-word because the action points back to the subject.",
    pathGroup: "grammar",
    coreContent: ["reflexive pronouns", "sich freuen", "sich erholen", "sich beeilen", "sich interessieren"],
    goetheB1Vocabulary: ["sich erholen", "sich freuen", "sich beeilen", "sich interessieren"],
    examRelevance: "Useful across B1 speaking and writing when discussing routines, interests, feelings, and plans.",
    dailyLifeExtension: ["Talk naturally about hobbies, plans, recovery, and personal interests."],
    commonMistakes: ["Dropping the reflexive pronoun because English does not need it."],
    priority: "high",
  },
  {
    lessonNo: 2,
    id: "b1-catalog-reflexive-verbs-2",
    titleEn: "Reflexive Verbs Part 2",
    titleDe: "Reflexivverben Teil 2",
    plainLanguageHook: "Some self-verbs absolutely require the self-word, while others change meaning depending on it.",
    pathGroup: "grammar",
    coreContent: ["true reflexive verbs", "reflexive verb variants", "sich konzentrieren", "sich waschen"],
    goetheB1Vocabulary: ["sich konzentrieren", "sich waschen", "sich ärgern"],
    examRelevance: "Prevents omission and overcorrection errors in B1 production.",
    dailyLifeExtension: ["Talk about emotions and personal care routines accurately."],
    commonMistakes: ["Removing the pronoun from true reflexive verbs."],
    priority: "medium",
  },
  {
    lessonNo: 3,
    id: "b1-catalog-reciprocal-verbs",
    titleEn: "Reciprocal Verbs",
    titleDe: "Reziproke Verben",
    plainLanguageHook: "Use this when two or more people do something to each other.",
    pathGroup: "grammar",
    coreContent: ["mutual actions", "wir treffen uns", "sie kennen sich", "einander"],
    goetheB1Vocabulary: ["sich treffen", "sich kennen", "einander"],
    examRelevance: "Helpful for reading and speaking about relationships and meetings.",
    dailyLifeExtension: ["Talk about friendships, meetings, colleagues, and relationships."],
    commonMistakes: ["Confusing reciprocal meaning with self-directed reflexive meaning."],
    priority: "medium",
  },
  {
    lessonNo: 4,
    id: "b1-catalog-noun-verb-combinations",
    titleEn: "Noun-Verb Combinations",
    titleDe: "Nomen-Verb-Verbindungen",
    plainLanguageHook: "German often uses a noun plus helper verb, like making a decision instead of just deciding.",
    pathGroup: "vocabulary",
    coreContent: ["eine Entscheidung treffen", "Rücksicht nehmen", "in Kontakt treten", "Platz nehmen"],
    goetheB1Vocabulary: ["eine Entscheidung treffen", "Rücksicht nehmen", "in Kontakt treten", "Platz nehmen"],
    examRelevance: "Important for B1 reading of formal and newspaper-style texts.",
    dailyLifeExtension: ["Sounds more polished in workplace and service contexts."],
    commonMistakes: ["Translating directly and saying eine Entscheidung machen instead of treffen."],
    priority: "high",
  },
  {
    lessonNo: 5,
    id: "b1-catalog-lassen",
    titleEn: "The Verb lassen",
    titleDe: "Das Verb lassen",
    plainLanguageHook: "Use lassen to say you let something happen or have something done by someone else.",
    pathGroup: "grammar",
    coreContent: ["lassen + infinitive", "to let/allow", "to have something done"],
    goetheB1Vocabulary: ["lassen", "lässt"],
    examRelevance: "Common in B1 texts about services, permissions, and delegated tasks.",
    dailyLifeExtension: ["Ich lasse meine Haare schneiden. Ich lasse das Auto reparieren."],
    commonMistakes: ["Using a heavy passive where lassen + infinitive is more natural."],
    priority: "high",
  },
  {
    lessonNo: 6,
    id: "b1-catalog-sich-lassen-passive",
    titleEn: "Passive with sich lassen",
    titleDe: "Passiv mit sich lassen",
    plainLanguageHook: "This says something can be done without naming who does it.",
    pathGroup: "grammar",
    coreContent: ["sich lassen + infinitive", "possibility", "natural passive alternative"],
    goetheB1Vocabulary: ["lässt sich", "öffnen", "reinigen"],
    examRelevance: "B1 style upgrade for writing and reading product/instruction texts.",
    dailyLifeExtension: ["Das lässt sich gut reinigen. Die Tür lässt sich leicht öffnen."],
    commonMistakes: ["Using full passive every time instead of the natural sich-lassen pattern."],
    priority: "medium",
  },
  {
    lessonNo: 8,
    id: "b1-catalog-weak-nouns",
    titleEn: "Weak Nouns / N-Declension",
    titleDe: "Schwache Nomen / N-Deklination",
    plainLanguageHook: "A small group of masculine nouns add -n or -en outside nominative.",
    pathGroup: "grammar",
    coreContent: ["der Kunde -> den Kunden", "der Kollege -> dem Kollegen", "der Mensch"],
    goetheB1Vocabulary: ["der Kunde", "der Kollege", "der Mensch", "der Name", "der Herr"],
    examRelevance: "Small but testable B1 grammar point, especially with work vocabulary.",
    dailyLifeExtension: ["Useful for workplace and service conversations."],
    commonMistakes: ["Saying den Kunde instead of den Kunden."],
    priority: "high",
  },
  {
    lessonNo: 9,
    id: "b1-catalog-genitive-prepositions",
    titleEn: "Genitive Prepositions",
    titleDe: "Genitivpräpositionen",
    plainLanguageHook: "These words express during, because of, and despite, and formal German expects genitive after them.",
    pathGroup: "grammar",
    coreContent: ["während", "wegen", "trotz", "genitive in formal writing"],
    goetheB1Vocabulary: ["während", "wegen", "trotz"],
    examRelevance: "B1 writing expects grammatically correct formal forms.",
    dailyLifeExtension: ["Useful for giving reasons, time context, and contrast."],
    commonMistakes: ["Using colloquial dative forms in formal writing."],
    priority: "medium",
  },
  {
    lessonNo: 11,
    id: "b1-catalog-da-compounds",
    titleEn: "da-Compounds",
    titleDe: "da-Wörter",
    plainLanguageHook: "German uses da + preposition to mean with it, about it, for it, and so on.",
    pathGroup: "grammar",
    coreContent: ["damit", "darüber", "dafür", "dabei", "dagegen", "r before vowel"],
    goetheB1Vocabulary: ["damit", "darüber", "dafür", "dabei", "dagegen"],
    examRelevance: "Makes B1 speaking and writing less repetitive and more natural.",
    dailyLifeExtension: ["Kannst du mir damit helfen? Ich freue mich darauf."],
    commonMistakes: ["Using da-compounds for people instead of things or ideas."],
    priority: "high",
  },
  {
    lessonNo: 13,
    id: "b1-catalog-wo-compounds",
    titleEn: "wo-Compounds",
    titleDe: "wo-Wörter",
    plainLanguageHook: "This is the question version of da-compounds: with what, about what, for what.",
    pathGroup: "grammar",
    coreContent: ["womit", "worüber", "wofür", "worauf", "r before vowel"],
    goetheB1Vocabulary: ["womit", "worüber", "wofür", "worauf"],
    examRelevance: "Useful for B1 Sprechen Teil 3 follow-up questions.",
    dailyLifeExtension: ["Ask clearer follow-up questions in real conversations."],
    commonMistakes: ["Using mit was instead of the more standard womit."],
    priority: "medium",
  },
  {
    lessonNo: 14,
    id: "b1-catalog-indem",
    titleEn: "Sentences with indem and dadurch, dass",
    titleDe: "Sätze mit indem und dadurch, dass",
    plainLanguageHook: "These say by doing something and explain the method.",
    pathGroup: "grammar",
    coreContent: ["indem", "dadurch, dass", "method clauses", "verb-final order"],
    goetheB1Vocabulary: ["indem", "dadurch dass"],
    examRelevance: "Useful in B1 opinion writing for explaining how something is achieved.",
    dailyLifeExtension: ["Explain methods and strategies at work or in learning."],
    commonMistakes: ["Confusing indem with während."],
    priority: "medium",
  },
  {
    lessonNo: 15,
    id: "b1-catalog-final-clauses",
    titleEn: "Final Clauses with um...zu and damit",
    titleDe: "Finalsätze mit um...zu und damit",
    plainLanguageHook: "Both express purpose; choose based on whether the subject is the same or different.",
    pathGroup: "grammar",
    coreContent: ["same subject -> um...zu", "different subject -> damit", "purpose clauses"],
    goetheB1Vocabulary: ["um zu", "damit"],
    examRelevance: "One of the most reliably tested B1 grammar contrasts.",
    dailyLifeExtension: ["Explain goals, plans, parenting, work intentions, and learning strategies."],
    commonMistakes: ["Using um...zu when the two actions have different subjects."],
    priority: "high",
  },
  {
    lessonNo: 16,
    id: "b1-catalog-ohne-zu-ohne-dass",
    titleEn: "ohne...zu vs ohne dass",
    titleDe: "ohne...zu oder ohne dass",
    plainLanguageHook: "Both mean without doing something; use the same subject rule as um...zu/damit.",
    pathGroup: "grammar",
    coreContent: ["same subject -> ohne...zu", "different subject -> ohne dass"],
    goetheB1Vocabulary: ["ohne zu", "ohne dass"],
    examRelevance: "Extends the same-subject/different-subject logic B1 expects.",
    dailyLifeExtension: ["Useful in storytelling, complaints, and explanations."],
    commonMistakes: ["Treating this as a separate rule instead of applying the same subject logic."],
    priority: "medium",
  },
  {
    lessonNo: 18,
    id: "b1-catalog-brauchen-zu",
    titleEn: "nicht/kein brauchen + zu",
    titleDe: "nicht/kein brauchen + zu",
    plainLanguageHook: "A smoother way to say you do not need to do something.",
    pathGroup: "grammar",
    coreContent: ["nicht brauchen + zu + infinitive", "formal writing", "equivalent to nicht müssen"],
    goetheB1Vocabulary: ["brauchen"],
    examRelevance: "Useful style upgrade in B1 writing.",
    dailyLifeExtension: ["Recognise colloquial versions where zu is dropped, but write it correctly."],
    commonMistakes: ["Dropping zu in writing because spoken German often drops it."],
    priority: "medium",
  },
  {
    lessonNo: 21,
    id: "b1-catalog-zustandspassiv",
    titleEn: "Static Passive",
    titleDe: "Zustandspassiv",
    plainLanguageHook: "This describes the result state, not the action happening.",
    pathGroup: "grammar",
    coreContent: ["sein + Partizip II", "state passive", "contrast with werden-passive"],
    goetheB1Vocabulary: ["geschlossen", "reserviert", "geöffnet"],
    examRelevance: "Important for distinguishing state vs process in B1 reading.",
    dailyLifeExtension: ["Understand signs, notices, reservations, and status descriptions."],
    commonMistakes: ["Using werden when describing a static result."],
    priority: "high",
  },
  {
    lessonNo: 23,
    id: "b1-catalog-konjunktiv-ii",
    titleEn: "Konjunktiv II — Verb Conjugation",
    titleDe: "Konjunktiv II",
    plainLanguageHook: "This is German's imaginary-world mode for wishes, polite requests, and hypothetical situations.",
    pathGroup: "grammar",
    coreContent: ["wäre", "hätte", "könnte", "müsste", "würde + infinitive", "polite requests"],
    goetheB1Vocabulary: ["wäre", "hätte", "könnte", "müsste", "dürfte", "würde"],
    examRelevance: "Defining B1 grammar for speaking, writing, planning, and polite requests.",
    dailyLifeExtension: ["Ich würde gerne..., Das wäre toll, Könntest du...?"],
    commonMistakes: ["Overusing rare pure forms where würde + infinitive is more natural."],
    priority: "high",
  },
  {
    lessonNo: 24,
    id: "b1-catalog-konjunktiv-ii-past",
    titleEn: "Konjunktiv II Past",
    titleDe: "Konjunktiv II der Vergangenheit",
    plainLanguageHook: "Use this to imagine a different past: I would have done, I would have gone.",
    pathGroup: "grammar",
    coreContent: ["hätte/wäre + Partizip II", "regret", "past hypotheticals"],
    goetheB1Vocabulary: ["hätte gemacht", "wäre gegangen", "hätte gewusst"],
    examRelevance: "Useful in reflective speaking and opinion writing.",
    dailyLifeExtension: ["Das hätte ich nicht gedacht. Ich wäre lieber zu Hause geblieben."],
    commonMistakes: ["Trying to change the participle instead of only using hätte/wäre."],
    priority: "medium",
  },
  {
    lessonNo: 25,
    id: "b1-catalog-wishes-dreams",
    titleEn: "Wishes and Dreams with Konjunktiv II",
    titleDe: "Wünsche und Träume mit Konjunktiv II",
    plainLanguageHook: "Use this to say what you wish were true.",
    pathGroup: "exam",
    coreContent: ["Ich wünschte", "Wenn ich nur", "Wenn ich Zeit hätte, würde ich..."],
    goetheB1Vocabulary: ["ich wünschte", "wenn ich nur", "an deiner Stelle"],
    examRelevance: "Useful for B1 speaking presentations and discussion of hopes/ambitions.",
    dailyLifeExtension: ["Talk about real hopes, plans, and unreal wishes."],
    commonMistakes: ["Using present indicative for unreal wishes."],
    priority: "medium",
  },
  {
    lessonNo: 26,
    id: "b1-catalog-semi-formal-letter",
    titleEn: "Semi-Formal Letter",
    titleDe: "Halbformeller Brief",
    plainLanguageHook: "This matches the B1 writing task where you politely apologise, decline, or request something.",
    pathGroup: "exam",
    coreContent: ["greeting", "all content points", "register", "closing", "apology/request patterns"],
    goetheB1Vocabulary: ["Es tut mir leid, dass...", "Leider kann ich nicht...", "Ich hoffe auf Ihr Verständnis"],
    examRelevance: "Direct preparation for Goethe B1 Schreiben Teil 3.",
    dailyLifeExtension: ["Emails to landlords, doctors, offices, colleagues, and schools."],
    commonMistakes: ["Missing a required content point under time pressure."],
    priority: "high",
  }
];

export function getB1TopicCatalogByPriority(priority: GermanB1TopicCatalogItem["priority"]): GermanB1TopicCatalogItem[] {
  return germanB1TopicCatalog.filter((topic) => topic.priority === priority);
}

export function getB1TopicCatalogByGroup(group: GermanB1TopicCatalogItem["pathGroup"]): GermanB1TopicCatalogItem[] {
  return germanB1TopicCatalog.filter((topic) => topic.pathGroup === group);
}
