export interface GermanA1TopicCatalogItem {
  lessonNo: number;
  id: string;
  titleEn: string;
  titleDe: string;
  pathGroup: "foundation" | "grammar" | "survival" | "exam" | "vocabulary";
  goetheThemeAlignment: string[];
  examRelevance: string;
  dailyLifeExtension: string;
  commonMistakes: string[];
  priority: "low" | "medium" | "high";
}

export const germanA1TopicCatalog: GermanA1TopicCatalogItem[] = [
  {
    lessonNo: 1,
    id: "a1-catalog-greetings",
    titleEn: "Greetings",
    titleDe: "Begrüßungen",
    pathGroup: "foundation",
    goetheThemeAlignment: ["Person", "social contact"],
    examRelevance: "Useful for Sprechen Teil 1 and recognising register in Hören dialogues.",
    dailyLifeExtension: "Use formal greetings with officials, neighbours, doctors, and service staff.",
    commonMistakes: ["Using Hallo in formal offices where Guten Tag is safer.", "Using Tschüss where Auf Wiedersehen is more appropriate."],
    priority: "high",
  },
  {
    lessonNo: 2,
    id: "a1-catalog-common-phrases",
    titleEn: "Common Phrases",
    titleDe: "Häufige Redemittel",
    pathGroup: "foundation",
    goetheThemeAlignment: ["Person", "Dienstleistungen"],
    examRelevance: "Clarification phrases help in Sprechen and appear throughout Hören.",
    dailyLifeExtension: "Bitte, danke, Entschuldigung, and Wie bitte are high-frequency survival phrases.",
    commonMistakes: ["Forgetting bitte in requests, making the phrase sound like a command."],
    priority: "high",
  },
  {
    lessonNo: 3,
    id: "a1-catalog-numbers-1-20",
    titleEn: "Numbers 1-20",
    titleDe: "Zahlen 1-20",
    pathGroup: "foundation",
    goetheThemeAlignment: ["Wortgruppe: Zahlen"],
    examRelevance: "Sprechen Teil 1 can test numbers, phone numbers, and postal codes; Hören often tests prices and quantities.",
    dailyLifeExtension: "Needed for phone numbers, addresses, ages, and quantities.",
    commonMistakes: ["Confusing sechzehn and sechzig later when moving beyond 20."],
    priority: "high",
  },
  {
    lessonNo: 4,
    id: "a1-catalog-numbers-20-100",
    titleEn: "Numbers 20-100",
    titleDe: "Zahlen 20-100",
    pathGroup: "foundation",
    goetheThemeAlignment: ["Wortgruppe: Zahlen"],
    examRelevance: "Critical for prices, addresses, phone numbers, and times in Hören/Lesen.",
    dailyLifeExtension: "German compound numbers reverse English order: einundzwanzig = twenty-one.",
    commonMistakes: ["Saying zwanzig-ein instead of einundzwanzig."],
    priority: "high",
  },
  {
    lessonNo: 5,
    id: "a1-catalog-alphabet",
    titleEn: "Alphabet",
    titleDe: "Alphabet",
    pathGroup: "foundation",
    goetheThemeAlignment: ["Person", "spelling names"],
    examRelevance: "Sprechen Teil 1 explicitly asks learners to spell their name.",
    dailyLifeExtension: "Useful for spelling your name at doctors, banks, Bürgeramt, and by phone.",
    commonMistakes: ["Using English letter names instead of German letter names."],
    priority: "high",
  },
  {
    lessonNo: 6,
    id: "a1-catalog-introducing-yourself",
    titleEn: "Introducing Yourself",
    titleDe: "Sich vorstellen",
    pathGroup: "exam",
    goetheThemeAlignment: ["Person", "Name", "Herkunft", "Wohnort"],
    examRelevance: "This is directly tested in Sprechen Teil 1.",
    dailyLifeExtension: "Used in German class, work, neighbours, appointments, and official first-contact situations.",
    commonMistakes: ["Relying only on Ich bin for names instead of learning Ich heiße and Mein Name ist."],
    priority: "high",
  },
  {
    lessonNo: 7,
    id: "a1-catalog-getting-to-know-someone",
    titleEn: "Getting to Know Someone",
    titleDe: "Jemanden kennenlernen",
    pathGroup: "foundation",
    goetheThemeAlignment: ["Person", "Persönliche Beziehungen"],
    examRelevance: "Supports Sprechen Teil 2 question formation.",
    dailyLifeExtension: "Teaches du/Sie register decisions for daily and official interactions.",
    commonMistakes: ["Mixing du and Sie forms in the same interaction."],
    priority: "high",
  },
  {
    lessonNo: 8,
    id: "a1-catalog-wie-gehts",
    titleEn: "How are you?",
    titleDe: "Wie geht's?",
    pathGroup: "foundation",
    goetheThemeAlignment: ["Person", "small talk"],
    examRelevance: "Common opener in Hören and useful in Sprechen warm-up.",
    dailyLifeExtension: "Useful for polite small talk with neighbours, colleagues, and classmates.",
    commonMistakes: ["Saying Ich gehe gut instead of Mir geht es gut."],
    priority: "medium",
  },
  {
    lessonNo: 9,
    id: "a1-catalog-sentence-structure-1",
    titleEn: "Sentence Structure Part 1",
    titleDe: "Satzbau Teil 1",
    pathGroup: "grammar",
    goetheThemeAlignment: ["Grammar foundation"],
    examRelevance: "Verb-second word order affects every writing and speaking task.",
    dailyLifeExtension: "Needed for every clear German sentence.",
    commonMistakes: ["Heute ich lerne Deutsch instead of Heute lerne ich Deutsch."],
    priority: "high",
  },
  {
    lessonNo: 10,
    id: "a1-catalog-sentence-structure-2",
    titleEn: "Sentence Structure Part 2",
    titleDe: "Satzbau Teil 2",
    pathGroup: "grammar",
    goetheThemeAlignment: ["Grammar foundation"],
    examRelevance: "Improves Schreiben Teil 2 and Sprechen sentence accuracy.",
    dailyLifeExtension: "Builds reusable sentence patterns for daily communication.",
    commonMistakes: ["Forgetting to conjugate the verb when changing subject."],
    priority: "high",
  },
  {
    lessonNo: 12,
    id: "a1-catalog-haben-sein",
    titleEn: "haben and sein",
    titleDe: "haben und sein",
    pathGroup: "grammar",
    goetheThemeAlignment: ["Grammar foundation"],
    examRelevance: "Used across Sprechen, Schreiben, Hören, and Lesen.",
    dailyLifeExtension: "Needed to describe yourself, family, possessions, appointments, and states.",
    commonMistakes: ["Applying regular endings to irregular forms such as er haben instead of er hat."],
    priority: "high",
  },
  {
    lessonNo: 19,
    id: "a1-catalog-definite-articles",
    titleEn: "Definite Articles",
    titleDe: "Bestimmte Artikel",
    pathGroup: "grammar",
    goetheThemeAlignment: ["Grammar foundation"],
    examRelevance: "Article control is visible in Schreiben and Sprechen accuracy.",
    dailyLifeExtension: "Nouns must be learned with articles from day one: der Termin, die Rechnung, das Kind.",
    commonMistakes: ["Learning nouns without articles and guessing gender later."],
    priority: "high",
  },
  {
    lessonNo: 21,
    id: "a1-catalog-negative-articles",
    titleEn: "Negative Articles",
    titleDe: "Negative Artikel",
    pathGroup: "grammar",
    goetheThemeAlignment: ["Grammar foundation"],
    examRelevance: "nicht vs kein errors are common in A1 writing and speaking.",
    dailyLifeExtension: "Used for everyday refusals and constraints: keine Zeit, kein Termin, keine Plätze.",
    commonMistakes: ["Using nicht ein/eine instead of kein/keine."],
    priority: "high",
  },
  {
    lessonNo: 22,
    id: "a1-catalog-official-time",
    titleEn: "Official Time",
    titleDe: "Uhrzeit offiziell",
    pathGroup: "foundation",
    goetheThemeAlignment: ["Wortgruppe: Uhrzeit"],
    examRelevance: "Hören often tests appointment, train, bus, and office times.",
    dailyLifeExtension: "24-hour clock is used in transport schedules, offices, and appointments.",
    commonMistakes: ["Thinking in AM/PM instead of the German 24-hour system."],
    priority: "high",
  },
  {
    lessonNo: 23,
    id: "a1-catalog-informal-time",
    titleEn: "Informal Time",
    titleDe: "Uhrzeit inoffiziell",
    pathGroup: "foundation",
    goetheThemeAlignment: ["Wortgruppe: Uhrzeit"],
    examRelevance: "Spoken Hören dialogues may use halb, Viertel vor, and Viertel nach.",
    dailyLifeExtension: "Germans often say halb drei for 2:30, which is not intuitive for English speakers.",
    commonMistakes: ["Interpreting halb drei as 3:30 instead of 2:30."],
    priority: "high",
  },
  {
    lessonNo: 26,
    id: "a1-catalog-accusative-articles",
    titleEn: "Accusative Articles",
    titleDe: "Akkusativartikel",
    pathGroup: "grammar",
    goetheThemeAlignment: ["Grammar foundation"],
    examRelevance: "Accusative errors are very visible in Schreiben and Sprechen.",
    dailyLifeExtension: "Needed for shopping, ordering, appointments, and direct-object sentences.",
    commonMistakes: ["Forgetting der -> den/einen for masculine direct objects."],
    priority: "high",
  },
  {
    lessonNo: 29,
    id: "a1-catalog-w-fragen",
    titleEn: "W Questions",
    titleDe: "W-Fragen",
    pathGroup: "exam",
    goetheThemeAlignment: ["Sprechen", "question formation"],
    examRelevance: "Directly tested in Goethe A1 Sprechen Teil 2.",
    dailyLifeExtension: "Essential for asking for information: where, when, who, what, why, how.",
    commonMistakes: ["Confusing wo with wohin."],
    priority: "high",
  },
  {
    lessonNo: 30,
    id: "a1-catalog-restaurant",
    titleEn: "In a Restaurant",
    titleDe: "Im Restaurant",
    pathGroup: "survival",
    goetheThemeAlignment: ["Essen/Trinken", "Lokale"],
    examRelevance: "Restaurant scenes are common Hören/Sprechen contexts.",
    dailyLifeExtension: "Useful for ordering, asking for menu, paying, and understanding service interactions.",
    commonMistakes: ["Not using bitte in orders; confusing Rechnung and zahlen."],
    priority: "medium",
  },
  {
    lessonNo: 32,
    id: "a1-catalog-dative-articles",
    titleEn: "Dative Articles",
    titleDe: "Dativartikel",
    pathGroup: "grammar",
    goetheThemeAlignment: ["Grammar foundation"],
    examRelevance: "Dative appears in fixed prepositions and common verbs even at A1.",
    dailyLifeExtension: "Needed for mit dem Bus, beim Arzt, zum Bahnhof, and helping/giving patterns.",
    commonMistakes: ["Using accusative endings after dative prepositions."],
    priority: "medium",
  },
  {
    lessonNo: 40,
    id: "a1-catalog-directions",
    titleEn: "Giving Directions",
    titleDe: "Wegbeschreibung",
    pathGroup: "survival",
    goetheThemeAlignment: ["Reisen/Verkehr", "Dienstleistungen"],
    examRelevance: "Directions are useful in Hören and Sprechen request/response situations.",
    dailyLifeExtension: "Practical for transport, stations, offices, hospitals, and streets.",
    commonMistakes: ["Confusing links/rechts/geradeaus or using English word order."],
    priority: "medium",
  },
  {
    lessonNo: 43,
    id: "a1-catalog-health",
    titleEn: "Talking about Health",
    titleDe: "Über Gesundheit sprechen",
    pathGroup: "survival",
    goetheThemeAlignment: ["health", "daily life"],
    examRelevance: "Supports appointment writing and simple speaking tasks.",
    dailyLifeExtension: "Useful for doctor calls, pharmacy, Kita sick messages, and insurance interactions.",
    commonMistakes: ["Using Ich bin Schmerz instead of Ich habe Schmerzen."],
    priority: "high",
  },
  {
    lessonNo: 50,
    id: "a1-catalog-fixing-appointments",
    titleEn: "Fixing Appointments",
    titleDe: "Termine vereinbaren",
    pathGroup: "survival",
    goetheThemeAlignment: ["Person", "Dienstleistungen", "Uhrzeit"],
    examRelevance: "High-value for Hören, Schreiben, and Sprechen request tasks.",
    dailyLifeExtension: "Core German life skill for doctors, Bürgeramt, school/Kita, work, and services.",
    commonMistakes: ["Ich habe ein Termin instead of Ich habe einen Termin."],
    priority: "high",
  },
  {
    lessonNo: 61,
    id: "a1-catalog-form-filling",
    titleEn: "Filling up a Form",
    titleDe: "Ein Formular ausfüllen",
    pathGroup: "exam",
    goetheThemeAlignment: ["Schreiben Teil 1", "Person"],
    examRelevance: "Directly tested in Goethe A1 Schreiben Teil 1.",
    dailyLifeExtension: "Needed for Anmeldung, doctor intake, bank, school/Kita, and course registration.",
    commonMistakes: ["Confusing Vorname, Nachname, Geburtsort, Geburtsdatum."],
    priority: "high",
  },
  {
    lessonNo: 64,
    id: "a1-catalog-apartment-search",
    titleEn: "Looking for an Apartment",
    titleDe: "Wohnung suchen",
    pathGroup: "survival",
    goetheThemeAlignment: ["Wohnen", "Miete", "Wohnungswechsel"],
    examRelevance: "Wohnen is an official Goethe theme and appears in Lesen/Sprechen.",
    dailyLifeExtension: "Essential for German life: rent, lease, deposit, rooms, furnished/unfurnished.",
    commonMistakes: ["Confusing Kaltmiete and Warmmiete."],
    priority: "high",
  },
  {
    lessonNo: 65,
    id: "a1-catalog-train-ticket",
    titleEn: "Buying a Train Ticket",
    titleDe: "Eine Zugfahrkarte kaufen",
    pathGroup: "survival",
    goetheThemeAlignment: ["Reisen/Verkehr"],
    examRelevance: "Transport appears frequently in Hören announcements and Sprechen scenarios.",
    dailyLifeExtension: "Needed for Deutsche Bahn travel, platform changes, delays, and ticket buying.",
    commonMistakes: ["Not knowing einfach means one-way in ticket context."],
    priority: "high",
  }
];

export function getA1TopicCatalogByPriority(priority: GermanA1TopicCatalogItem["priority"]): GermanA1TopicCatalogItem[] {
  return germanA1TopicCatalog.filter((topic) => topic.priority === priority);
}

export function getA1TopicCatalogByGroup(group: GermanA1TopicCatalogItem["pathGroup"]): GermanA1TopicCatalogItem[] {
  return germanA1TopicCatalog.filter((topic) => topic.pathGroup === group);
}
