export interface GermanA2TopicCatalogItem {
  lessonNo: number;
  id: string;
  titleEn: string;
  titleDe: string;
  pathGroup: "grammar" | "exam" | "survival" | "vocabulary";
  goetheThemeAlignment: string[];
  coreContent: string[];
  goetheA2Vocabulary: string[];
  examRelevance: string;
  dailyLifeExtension: string[];
  commonMistakes: string[];
  priority: "low" | "medium" | "high";
}

export const germanA2TopicCatalog: GermanA2TopicCatalogItem[] = [
  {
    lessonNo: 1,
    id: "a2-catalog-self-introduction",
    titleEn: "Introducing Yourself (Goethe A2 style)",
    titleDe: "Sich vorstellen",
    pathGroup: "exam",
    goetheThemeAlignment: ["Person", "Sprechen Teil 1"],
    coreContent: ["Structured A2 self-introduction", "Profession, family status, hobbies", "Oral exam opening exchange"],
    goetheA2Vocabulary: ["sich vorstellen", "der Beruf", "der Familienstand"],
    examRelevance: "Directly supports Goethe A2 Sprechen Teil 1 question-answer exchange.",
    dailyLifeExtension: ["Useful for work, integration course, neighbours, and semi-formal introductions."],
    commonMistakes: ["Repeating only the A1-level introduction without A2 details such as profession or family status."],
    priority: "high",
  },
  {
    lessonNo: 2,
    id: "a2-catalog-character-traits",
    titleEn: "Character Traits",
    titleDe: "Charaktereigenschaften",
    pathGroup: "vocabulary",
    goetheThemeAlignment: ["Person", "personal characteristics"],
    coreContent: ["Describe personality", "Use sein + adjective", "Describe colleagues/family/friends"],
    goetheA2Vocabulary: ["freundlich", "geduldig", "ehrlich", "schüchtern", "lustig", "ruhig"],
    examRelevance: "Supports Sprechen Teil 2 personal monologues and Lesen text descriptions.",
    dailyLifeExtension: ["Useful for describing colleagues, friends, family, and social situations."],
    commonMistakes: ["Confusing similar adjectives such as schüchtern and sicher."],
    priority: "medium",
  },
  {
    lessonNo: 3,
    id: "a2-catalog-dass",
    titleEn: "Subordinate Clauses with dass",
    titleDe: "Nebensatz mit dass",
    pathGroup: "grammar",
    goetheThemeAlignment: ["Grammar foundation"],
    coreContent: ["dass introduces subordinate clause", "verb moves to the end", "distinguish main clause from subordinate clause"],
    goetheA2Vocabulary: ["dass", "glauben", "denken", "meinen", "hoffen"],
    examRelevance: "A2 examiners check verb-final placement in Schreiben and Sprechen.",
    dailyLifeExtension: ["Needed for opinions: Ich finde, dass... / Ich denke, dass..."],
    commonMistakes: ["Keeping verb-second order inside the dass-clause instead of moving the verb to the end."],
    priority: "high",
  },
  {
    lessonNo: 4,
    id: "a2-catalog-weil-da-denn",
    titleEn: "Causal Clauses: weil/da vs denn",
    titleDe: "Kausalsatz: weil, da, denn",
    pathGroup: "grammar",
    goetheThemeAlignment: ["Grammar foundation"],
    coreContent: ["weil/da are subordinate", "denn is coordinating", "different word order for the same English meaning because"],
    goetheA2Vocabulary: ["weil", "da", "denn"],
    examRelevance: "Classic A2 grammar contrast in writing and speaking.",
    dailyLifeExtension: ["Needed to explain delays, sickness, refusal, and reasons."],
    commonMistakes: ["Using verb-last word order after denn."],
    priority: "high",
  },
  {
    lessonNo: 5,
    id: "a2-catalog-adjective-endings-nominative",
    titleEn: "Adjective Endings — Nominative",
    titleDe: "Adjektivendungen im Nominativ",
    pathGroup: "grammar",
    goetheThemeAlignment: ["Grammar foundation"],
    coreContent: ["Weak/mixed/strong declension", "der gute Mann", "ein guter Mann", "guter Wein"],
    goetheA2Vocabulary: [],
    examRelevance: "Adjective endings are a defining A2 grammar challenge across Lesen and Schreiben.",
    dailyLifeExtension: ["Needed to describe people, products, places, and situations."],
    commonMistakes: ["Using one default adjective ending regardless of article type."],
    priority: "high",
  },
  {
    lessonNo: 6,
    id: "a2-catalog-adjective-endings-accusative",
    titleEn: "Adjective Endings — Accusative",
    titleDe: "Adjektivendungen im Akkusativ",
    pathGroup: "grammar",
    goetheThemeAlignment: ["Grammar foundation"],
    coreContent: ["Accusative adjective endings", "masculine direct object changes", "den guten / einen guten"],
    goetheA2Vocabulary: [],
    examRelevance: "Builds the case and adjective matrix expected at A2.",
    dailyLifeExtension: ["Shopping, ordering, and detailed direct-object descriptions."],
    commonMistakes: ["Forgetting masculine nouns change in accusative: den guten Wein."],
    priority: "high",
  },
  {
    lessonNo: 7,
    id: "a2-catalog-adjective-endings-dative",
    titleEn: "Adjective Endings — Dative",
    titleDe: "Adjektivendungen im Dativ",
    pathGroup: "grammar",
    goetheThemeAlignment: ["Grammar foundation"],
    coreContent: ["Dative adjective endings", "mostly -en pattern", "after dative prepositions"],
    goetheA2Vocabulary: [],
    examRelevance: "Completes the high-frequency A2 adjective ending set.",
    dailyLifeExtension: ["Useful after mit, bei, zu, von, aus, nach."],
    commonMistakes: ["Overcomplicating dative endings instead of learning the regular -en pattern."],
    priority: "high",
  },
  {
    lessonNo: 8,
    id: "a2-catalog-wenn",
    titleEn: "Conditional Clauses with wenn",
    titleDe: "Nebensatz mit wenn",
    pathGroup: "grammar",
    goetheThemeAlignment: ["Grammar foundation", "planning"],
    coreContent: ["wenn means if/when", "verb-last subordinate clause", "verb-second echo in following main clause"],
    goetheA2Vocabulary: ["wenn"],
    examRelevance: "Useful in Sprechen Teil 3 planning and written explanations.",
    dailyLifeExtension: ["Planning: Wenn ich Zeit habe, komme ich mit."],
    commonMistakes: ["Forgetting the verb-second flip after a fronted wenn-clause."],
    priority: "high",
  },
  {
    lessonNo: 11,
    id: "a2-catalog-comparative-superlative-1",
    titleEn: "Comparative and Superlative Part 1",
    titleDe: "Komparativ und Superlativ Teil 1",
    pathGroup: "grammar",
    goetheThemeAlignment: ["Freizeit", "opinions", "comparison"],
    coreContent: ["-er comparative", "am ... -sten superlative", "regular patterns"],
    goetheA2Vocabulary: ["schnell", "schneller", "am schnellsten", "größer", "am größten"],
    examRelevance: "Standard A2 speaking/writing structure for opinions and comparisons.",
    dailyLifeExtension: ["Shopping, preferences, choices, travel, apartment comparisons."],
    commonMistakes: ["Missing umlaut changes in one-syllable adjectives."],
    priority: "high",
  },
  {
    lessonNo: 12,
    id: "a2-catalog-comparative-superlative-2",
    titleEn: "Comparative and Superlative Part 2",
    titleDe: "Komparativ und Superlativ Teil 2",
    pathGroup: "grammar",
    goetheThemeAlignment: ["opinions", "preferences"],
    coreContent: ["irregular forms", "gut/besser/am besten", "gern/lieber/am liebsten"],
    goetheA2Vocabulary: ["besser", "am besten", "mehr", "am meisten", "lieber", "am liebsten"],
    examRelevance: "High-frequency A2 forms across all modules.",
    dailyLifeExtension: ["Daily preferences: Ich trinke lieber Tee. Am liebsten esse ich..."],
    commonMistakes: ["Regularising irregular forms, e.g. guter instead of besser."],
    priority: "high",
  },
  {
    lessonNo: 13,
    id: "a2-catalog-obwohl",
    titleEn: "Concessive Clauses with obwohl",
    titleDe: "Nebensatz mit obwohl",
    pathGroup: "grammar",
    goetheThemeAlignment: ["contrast", "opinion"],
    coreContent: ["obwohl means although", "verb-last word order", "contrastive statements"],
    goetheA2Vocabulary: ["obwohl"],
    examRelevance: "Shows nuanced sentence-building beyond A1.",
    dailyLifeExtension: ["Useful for realistic statements: Ich mag meinen Job, obwohl er stressig ist."],
    commonMistakes: ["Confusing obwohl with trotzdem word order."],
    priority: "high",
  },
  {
    lessonNo: 14,
    id: "a2-catalog-deshalb-trotzdem",
    titleEn: "deshalb and trotzdem",
    titleDe: "deshalb und trotzdem",
    pathGroup: "grammar",
    goetheThemeAlignment: ["connectors", "argument structure"],
    coreContent: ["deshalb consequence", "trotzdem contrast", "both trigger verb-second/inversion"],
    goetheA2Vocabulary: ["deshalb", "trotzdem", "deswegen", "darum"],
    examRelevance: "Important connector contrast for A2 writing and speaking.",
    dailyLifeExtension: ["Used to connect reasons and consequences in daily explanations."],
    commonMistakes: ["Using verb-last after deshalb/trotzdem as if they were subordinating conjunctions."],
    priority: "high",
  },
  {
    lessonNo: 15,
    id: "a2-catalog-werden",
    titleEn: "The Verb werden",
    titleDe: "Das Verb werden",
    pathGroup: "grammar",
    goetheThemeAlignment: ["Arbeit/Beruf", "future plans"],
    coreContent: ["to become", "future auxiliary", "passive auxiliary exposure"],
    goetheA2Vocabulary: ["werden"],
    examRelevance: "Useful for career goals and future plans in speaking/writing.",
    dailyLifeExtension: ["Talk about plans, career changes, and future actions."],
    commonMistakes: ["Confusing werden with sein."],
    priority: "medium",
  },
  {
    lessonNo: 16,
    id: "a2-catalog-indirect-questions",
    titleEn: "Indirect Questions",
    titleDe: "Indirekte Fragen",
    pathGroup: "grammar",
    goetheThemeAlignment: ["polite questions", "services"],
    coreContent: ["Ich möchte wissen, ob...", "Können Sie mir sagen, wann...", "verb-final word order"],
    goetheA2Vocabulary: ["ob", "wann", "wo", "wie", "wissen"],
    examRelevance: "Useful for polite email/request tasks and speaking interactions.",
    dailyLifeExtension: ["Essential for doctors, offices, service calls, and appointments."],
    commonMistakes: ["Keeping direct-question word order inside indirect questions."],
    priority: "high",
  },
  {
    lessonNo: 18,
    id: "a2-catalog-relative-nominative",
    titleEn: "Relative Clauses — Nominative",
    titleDe: "Relativsätze im Nominativ",
    pathGroup: "grammar",
    goetheThemeAlignment: ["description", "reading"],
    coreContent: ["relative pronouns der/die/das", "describe people/things", "verb at end"],
    goetheA2Vocabulary: ["der", "die", "das"],
    examRelevance: "Important for reading comprehension and more advanced descriptions.",
    dailyLifeExtension: ["Describe people, items, apartments, and services more naturally."],
    commonMistakes: ["Using English-style who/which patterns instead of German relative pronouns."],
    priority: "medium",
  },
  {
    lessonNo: 24,
    id: "a2-catalog-preterite-modal-verbs",
    titleEn: "Preterite Modal Verbs",
    titleDe: "Präteritum der Modalverben",
    pathGroup: "grammar",
    goetheThemeAlignment: ["past narration"],
    coreContent: ["konnte", "musste", "wollte", "sollte", "durfte"],
    goetheA2Vocabulary: ["konnte", "musste", "wollte", "durfte"],
    examRelevance: "Useful for telling past experiences in speaking and writing.",
    dailyLifeExtension: ["Explain what you could/had to/wanted to do in past situations."],
    commonMistakes: ["Trying to use Perfekt for all modal-verb past meanings."],
    priority: "medium",
  },
  {
    lessonNo: 27,
    id: "a2-catalog-als",
    titleEn: "Subordinate Clauses with als",
    titleDe: "Nebensatz mit als",
    pathGroup: "grammar",
    goetheThemeAlignment: ["past narration"],
    coreContent: ["als for one-time past events", "verb-final clause", "childhood narration"],
    goetheA2Vocabulary: ["als", "früher", "Kindheit"],
    examRelevance: "Useful in Sprechen Teil 2 when describing your life or past experiences.",
    dailyLifeExtension: ["Talk about childhood, past residence, previous jobs, earlier routines."],
    commonMistakes: ["Using wenn instead of als for one-time past events."],
    priority: "medium",
  },
  {
    lessonNo: 29,
    id: "a2-catalog-advantages-disadvantages",
    titleEn: "City vs Countryside / Advantages and Disadvantages",
    titleDe: "Stadt oder Land / Vor- und Nachteile",
    pathGroup: "exam",
    goetheThemeAlignment: ["Wohnen", "opinions", "comparison"],
    coreContent: ["advantages/disadvantages", "opinion structure", "comparison language"],
    goetheA2Vocabulary: ["der Vorteil", "der Nachteil", "die Stadt", "das Land"],
    examRelevance: "A2 speaking/writing often asks for personal opinions with simple reasons.",
    dailyLifeExtension: ["Discuss where you live and why you prefer a city/neighbourhood."],
    commonMistakes: ["Listing vocabulary without giving clear reasons using weil/deshalb."],
    priority: "high",
  },
  {
    lessonNo: 30,
    id: "a2-catalog-infinitive-with-zu",
    titleEn: "Infinitive with zu",
    titleDe: "Infinitiv mit zu",
    pathGroup: "grammar",
    goetheThemeAlignment: ["grammar bridge"],
    coreContent: ["es ist wichtig, ... zu", "beginnen/versuchen/vergessen + zu", "sentence expansion"],
    goetheA2Vocabulary: ["zu", "versuchen", "beginnen", "vergessen"],
    examRelevance: "Helps produce longer, more natural A2 writing/speaking sentences.",
    dailyLifeExtension: ["Useful for goals and plans: Ich versuche, jeden Tag Deutsch zu lernen."],
    commonMistakes: ["Forgetting zu before the infinitive."],
    priority: "medium",
  },
  {
    lessonNo: 34,
    id: "a2-catalog-two-way-prepositions",
    titleEn: "Two-way Prepositions",
    titleDe: "Wechselpräpositionen",
    pathGroup: "grammar",
    goetheThemeAlignment: ["Wohnen", "Reisen/Verkehr"],
    coreContent: ["location uses dative", "movement/direction uses accusative", "in/an/auf/unter/über/vor/hinter/neben/zwischen"],
    goetheA2Vocabulary: ["in", "an", "auf", "unter", "über", "vor", "hinter", "neben", "zwischen"],
    examRelevance: "Important for reading, writing, picture description, and directions.",
    dailyLifeExtension: ["Apartment, directions, furniture, transport, appointments."],
    commonMistakes: ["Using dative/accusative randomly instead of deciding location vs movement."],
    priority: "high",
  },
  {
    lessonNo: 36,
    id: "a2-catalog-polite-requests",
    titleEn: "Polite Requests with Konjunktiv II",
    titleDe: "Höfliche Bitten mit Konjunktiv II",
    pathGroup: "survival",
    goetheThemeAlignment: ["services", "requests", "Sprechen/Schreiben"],
    coreContent: ["könnten", "würden", "ich hätte gern", "polite request structure"],
    goetheA2Vocabulary: ["könnten", "würden", "hätte gern"],
    examRelevance: "Useful for A2 email requests and speaking roleplays.",
    dailyLifeExtension: ["Doctors, Bürgeramt, shops, landlord, work requests."],
    commonMistakes: ["Using direct imperative where a polite request is expected."],
    priority: "high",
  },
  {
    lessonNo: 37,
    id: "a2-catalog-picture-description",
    titleEn: "Describing a Picture",
    titleDe: "Ein Bild beschreiben",
    pathGroup: "exam",
    goetheThemeAlignment: ["Sprechen", "description"],
    coreContent: ["in the foreground/background", "people/actions/places", "simple assumptions"],
    goetheA2Vocabulary: ["im Vordergrund", "im Hintergrund", "man sieht", "vielleicht"],
    examRelevance: "Useful for oral exam style description and speaking development.",
    dailyLifeExtension: ["Describe situations, photos, objects, and apartment/workplace scenes."],
    commonMistakes: ["Only listing nouns instead of forming full sentences."],
    priority: "medium",
  },
  {
    lessonNo: 39,
    id: "a2-catalog-passive-1",
    titleEn: "Passive Voice Part 1",
    titleDe: "Passiv Teil 1",
    pathGroup: "grammar",
    goetheThemeAlignment: ["formal notices", "instructions"],
    coreContent: ["werden + Partizip II", "process description", "public/service contexts"],
    goetheA2Vocabulary: ["werden", "geöffnet", "geschlossen", "gemacht"],
    examRelevance: "Helpful for reading notices and formal service texts.",
    dailyLifeExtension: ["Understand official signs, instructions, and notices."],
    commonMistakes: ["Confusing passive werden with future werden."],
    priority: "medium",
  },
  {
    lessonNo: 41,
    id: "a2-catalog-recipe-writing",
    titleEn: "Writing a Recipe / Instructions",
    titleDe: "Ein Rezept schreiben",
    pathGroup: "exam",
    goetheThemeAlignment: ["instructions", "food", "daily life"],
    coreContent: ["imperative/instruction style", "sequence markers", "ingredients and quantities"],
    goetheA2Vocabulary: ["zuerst", "danach", "dann", "zum Schluss", "kochen", "schneiden"],
    examRelevance: "Supports instruction reading/writing and sequence language.",
    dailyLifeExtension: ["Food, cooking, explaining procedures, household communication."],
    commonMistakes: ["Missing sequence connectors such as zuerst/dann/danach."],
    priority: "medium",
  },
  {
    lessonNo: 50,
    id: "a2-catalog-authentic-dialogues",
    titleEn: "10 Authentic Dialogues",
    titleDe: "10 authentische Dialoge",
    pathGroup: "exam",
    goetheThemeAlignment: ["Hören", "Sprechen", "daily conversation"],
    coreContent: ["realistic A2 dialogues", "listening comprehension", "roleplay and repetition"],
    goetheA2Vocabulary: [],
    examRelevance: "Consolidates A2 listening/speaking patterns for exam readiness.",
    dailyLifeExtension: ["Simulates daily-life interaction speed and context."],
    commonMistakes: ["Understanding individual words but missing the purpose or next action."],
    priority: "high",
  }
];

export function getA2TopicCatalogByPriority(priority: GermanA2TopicCatalogItem["priority"]): GermanA2TopicCatalogItem[] {
  return germanA2TopicCatalog.filter((topic) => topic.priority === priority);
}

export function getA2TopicCatalogByGroup(group: GermanA2TopicCatalogItem["pathGroup"]): GermanA2TopicCatalogItem[] {
  return germanA2TopicCatalog.filter((topic) => topic.pathGroup === group);
}
