import type { GermanA1PdfStudyNotePage } from "./types";

export const germanA1PdfStudyNotesBatch08: GermanA1PdfStudyNotePage[] = [
  {
    "batch": "Batch 08",
    "sourcePages": "source pages 106-118",
    "page": 1,
    "heading": "1. A1 Sentence Order - Core Patterns",
    "text": "A1 German Typed Study Notes\nPage 1\n A1 German Notes - Batch 08\n Typed study notes from handwritten source pages 106-118. Corrected and organized for self-study.\nRevision, exam speaking prompts, grammar checklist, and mixed\npractice\nNote: The original file is handwritten and scanned. These notes preserve the learning topics and examples, while\ncorrecting obvious spelling, article, capitalization, and sentence-order issues where needed.\n1. A1 Sentence Order - Core Patterns\nGerman sentence order is the backbone of A1 grammar. Keep the conjugated verb in position 2 in\nstatements.\nPattern\nGerman example\nEnglish\nSubject + verb + rest\nIch wohne in Berlin.\nI live in Berlin.\nTime + verb + subject + rest\nHeute lerne ich Deutsch.\nToday I learn German.\nQuestion word + verb + subject\nWo wohnen Sie?\nWhere do you live?\nVerb + subject ...?\nSprechen Sie Deutsch?\nDo you speak German?\nModal + infinitive at end\nIch kann Deutsch sprechen.\nI can speak German.\n2. Speaking Exam: Introduce Yourself\nUse this as a clean model for A1 speaking practice.\nExamples\nGuten Tag. Mein Name ist Alex George. Ich komme aus Indien und wohne in Berlin. Ich bin Software\nEngineer von Beruf. Ich spreche Malayalam, Englisch und ein bisschen Deutsch. Meine Hobbys sind\nLesen, Reisen und Musik hören. Ich lerne Deutsch, weil ich in Deutschland lebe und arbeiten möchte.\n3. Important Question Bank\nGerman question\nModel answer\nWie heißen Sie?\nIch heiße Alex.\nWoher kommen Sie?\nIch komme aus Indien.\nWo wohnen Sie?\nIch wohne in Berlin.\nWas sind Sie von Beruf?\nIch bin Ingenieur.\nWelche Sprachen sprechen Sie?\nIch spreche Malayalam, Englisch und etwas Deutsch.\nWas sind Ihre Hobbys?\nMeine Hobbys sind Lesen und Reisen.\nHaben Sie Kinder?\nJa, ich habe ein Kind. / Nein, ich habe kein Kind.\nWarum lernen Sie Deutsch?\nIch lerne Deutsch, weil ich in Deutschland lebe.\nWann lernen Sie Deutsch?\nIch lerne Deutsch am Abend.\nWas essen Sie gern?\nIch esse gern Reis.\n4. Grammar Revision Checklist"
  },
  {
    "batch": "Batch 08",
    "sourcePages": "source pages 106-118",
    "page": 2,
    "heading": "5. Mixed Practice",
    "text": "A1 German Typed Study Notes\nPage 2\n Nouns are capitalized and need articles.\n Verb is second in statements.\n Questions usually start with question word + verb, or verb first for yes/no questions.\n Use Sie for formal situations.\n Use kein/keine for noun negation and nicht for verbs/adjectives.\n Masculine accusative changes: der -> den, ein -> einen.\n Modal verbs send the second verb to the end.\n Separable verbs split: Ich stehe auf.\n5. Mixed Practice\nPractice\n1) Translate: I live in Berlin.\n2) Make a question: Sie wohnen in Berlin.\n3) Fill in: Ich ___ Deutsch sprechen. (können)\n4) Choose: Ich habe (ein/einen) Bruder.\n5) Negate: Das ist eine Tasche.\n6) Put the time first: Ich lerne Deutsch am Abend.\n7) Answer: Warum lernen Sie Deutsch?\nAnswer key\n1) Ich wohne in Berlin.\n2) Wohnen Sie in Berlin? / Wo wohnen Sie?\n3) Ich kann Deutsch sprechen.\n4) Ich habe einen Bruder.\n5) Das ist keine Tasche.\n6) Am Abend lerne ich Deutsch.\n7) Example: Ich lerne Deutsch, weil ich in Deutschland lebe.\n6. Final Mini Dialogues\nExamples\nA: Guten Morgen. Wie heißen Sie? B: Ich heiße Alex. A: Woher kommen Sie? B: Ich komme aus Indien.\nA: Entschuldigung, wo ist der Bahnhof? B: Gehen Sie geradeaus und dann links. Der Bahnhof ist neben\ndem Supermarkt.\nA: Was möchten Sie? B: Ich möchte einen Kaffee und ein Wasser, bitte. A: Sonst noch etwas? B: Nein,\ndanke."
  }
];
